@startuml State Diagram

skin rose
'left to right direction
hide empty description
!theme reddress-lightgreen
title FB_SelfTest State Diagram



state FB_SelfTest{

state eInnerState #03adfc {
	[*] --> eInnerState_Idle : START
	state eInnerState_Idle{
	state eInnerState_Idle_Node_0 <<choice>>
	[*] --> eInnerState_Idle_Node_0 : START
	eInnerState_Idle_Node_0 --> [*] : (bStart)
	}
	state eInnerState_HomeStepper1{
	state eInnerState_HomeStepper1_Node_0 <<choice>>
	[*] --> eInnerState_HomeStepper1_Node_0 : START
		state eInnerState_HomeStepper1_Node_1 <<choice>>
	eInnerState_HomeStepper1_Node_1 --> [*] : (NOT (fbStepper.bError))
	}
	state eInnerState_HomeStepper2{
	state eInnerState_HomeStepper2_Node_0 <<choice>>
	[*] --> eInnerState_HomeStepper2_Node_0 : START
		state eInnerState_HomeStepper2_Node_1 <<choice>>
			state eInnerState_HomeStepper2_Node_2 <<choice>>
	eInnerState_HomeStepper2_Node_2 --> [*] : (fbStepper.Homed)
	}
	state eInnerState_HomeLinearActuator1{
	state eInnerState_HomeLinearActuator1_Node_0 <<choice>>
	[*] --> eInnerState_HomeLinearActuator1_Node_0 : START
		state eInnerState_HomeLinearActuator1_Node_1 <<choice>>
	eInnerState_HomeLinearActuator1_Node_1 --> [*] : (NOT (fbLinearActuator.bError))
	}
	state eInnerState_HomeLinearActuator2{
	state eInnerState_HomeLinearActuator2_Node_0 <<choice>>
	[*] --> eInnerState_HomeLinearActuator2_Node_0 : START
		state eInnerState_HomeLinearActuator2_Node_1 <<choice>>
			state eInnerState_HomeLinearActuator2_Node_2 <<choice>>
	eInnerState_HomeLinearActuator2_Node_2 --> [*] : (fbLinearActuator.Homed)
	}
	state eInnerState_SetupEncoders1{
	state eInnerState_SetupEncoders1_Node_0 <<choice>>
	[*] --> eInnerState_SetupEncoders1_Node_0 : START
		state eInnerState_SetupEncoders1_Node_1 <<choice>>
	eInnerState_SetupEncoders1_Node_1 --> [*] : (NOT (fbJointSR.bError))
	}
	state eInnerState_SetupEncoders2{
	state eInnerState_SetupEncoders2_Node_0 <<choice>>
	[*] --> eInnerState_SetupEncoders2_Node_0 : START
		state eInnerState_SetupEncoders2_Node_1 <<choice>>
			state eInnerState_SetupEncoders2_Node_2 <<choice>>
	eInnerState_SetupEncoders2_Node_2 --> [*] : (fbJointSR.Calibrated)
	}
	state eInnerState_CheckAbsEncoderOffsets1{
	}
	state eInnerState_CheckAbsEncoderOffsets2{
	}
	state eInnerState_WrapUp{
	}
	}
	eInnerState_Idle --> eInnerState_HomeStepper1 : (bStart)
	eInnerState_HomeStepper1_Node_0 --> eInnerState_HomeStepper1_Node_1 : (NOT (fbStepper.Busy))
	eInnerState_HomeStepper1 --> eInnerState_HomeStepper2 : (NOT (fbStepper.bError))
	eInnerState_HomeStepper2_Node_0 --> eInnerState_HomeStepper2_Node_1 : (NOT (fbStepper.Busy))
	eInnerState_HomeStepper2_Node_1 --> eInnerState_HomeStepper2_Node_2 : (NOT (fbStepper.bError))
	eInnerState_HomeStepper2 --> eInnerState_HomeLinearActuator1 : (fbStepper.Homed)
	eInnerState_HomeLinearActuator1_Node_0 --> eInnerState_HomeLinearActuator1_Node_1 : (NOT (fbLinearActuator.Busy))
	eInnerState_HomeLinearActuator1 --> eInnerState_HomeLinearActuator2 : (NOT (fbLinearActuator.bError))
	eInnerState_HomeLinearActuator2_Node_0 --> eInnerState_HomeLinearActuator2_Node_1 : (NOT (fbLinearActuator.Busy))
	eInnerState_HomeLinearActuator2_Node_1 --> eInnerState_HomeLinearActuator2_Node_2 : (NOT (fbLinearActuator.bError))
	eInnerState_HomeLinearActuator2 --> eInnerState_SetupEncoders1 : (fbLinearActuator.Homed)
	eInnerState_SetupEncoders1_Node_0 --> eInnerState_SetupEncoders1_Node_1 : (NOT (fbJointSR.Busy))
	eInnerState_SetupEncoders1 --> eInnerState_SetupEncoders2 : (NOT (fbJointSR.bError))
	eInnerState_SetupEncoders2_Node_0 --> eInnerState_SetupEncoders2_Node_1 : (NOT (fbJointSR.Busy))
	eInnerState_SetupEncoders2_Node_1 --> eInnerState_SetupEncoders2_Node_2 : (NOT (fbJointSR.bError))
	eInnerState_SetupEncoders2 --> eInnerState_CheckAbsEncoderOffsets1 : (fbJointSR.Calibrated)


}

@enduml
