@startuml State Diagram

!theme plain
'skin rose
'left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_AllJoints State Diagram



state FB_AllJoints{

state eInnerState #84b1f5 {
	[*] --> eInnerState_Idle : START
	state eInnerState_Idle #lightblue {
state "ERROR" as eInnerState_Idle_ERROR <<exitPoint>> #ff3333
	state eInnerState_Idle_Node_0 <<choice>>
	[*] ---> eInnerState_Idle_Node_0 : START
	eInnerState_Idle_Node_0 ---> [*] : (bStartCalibration)
		state eInnerState_Idle_Node_1 <<choice>>
	}
	state eInnerState_CalibrateAllButElbow1 #lightblue {
state "ERROR" as eInnerState_CalibrateAllButElbow1_ERROR <<exitPoint>> #ff3333
	state eInnerState_CalibrateAllButElbow1_Node_0 <<choice>>
	[*] ---> eInnerState_CalibrateAllButElbow1_Node_0 : START
	eInnerState_CalibrateAllButElbow1_Node_0 ---> [*] : (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready)
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_CalibrateAllButElbow1_Node_1 
	}
	state eInnerState_CalibrateAllButElbow2 #lightblue {
state "ERROR" as eInnerState_CalibrateAllButElbow2_ERROR <<exitPoint>> #ff3333
	state eInnerState_CalibrateAllButElbow2_Node_0 <<choice>>
	[*] ---> eInnerState_CalibrateAllButElbow2_Node_0 : START
	eInnerState_CalibrateAllButElbow2_Node_0 ---> [*] : (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready)
		state eInnerState_CalibrateAllButElbow2_Node_1 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_CalibrateAllButElbow2_Node_2 
		state eInnerState_CalibrateAllButElbow2_Node_3 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_CalibrateAllButElbow2_Node_4 
		state eInnerState_CalibrateAllButElbow2_Node_5 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_CalibrateAllButElbow2_Node_6 
		state eInnerState_CalibrateAllButElbow2_Node_7 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_CalibrateAllButElbow2_Node_8 
		state eInnerState_CalibrateAllButElbow2_Node_9 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_CalibrateAllButElbow2_Node_10 
	}
	state eInnerState_CalibrateElbow1 #lightblue {
state "ERROR" as eInnerState_CalibrateElbow1_ERROR <<exitPoint>> #ff3333
	state eInnerState_CalibrateElbow1_Node_0 <<choice>>
	[*] ---> eInnerState_CalibrateElbow1_Node_0 : START
	eInnerState_CalibrateElbow1_Node_0 ---> [*] : (fbJointE.Ready)
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_CalibrateElbow1_Node_1 
	}
	state eInnerState_CalibrateElbow2 #lightblue {
state "ERROR" as eInnerState_CalibrateElbow2_ERROR <<exitPoint>> #ff3333
	state eInnerState_CalibrateElbow2_Node_0 <<choice>>
	[*] ---> eInnerState_CalibrateElbow2_Node_0 : START
		state eInnerState_CalibrateElbow2_Node_1 <<choice>>
		state "fbEventHandler(REQUEST_COMPLETED)" as eInnerState_CalibrateElbow2_Node_2 
	eInnerState_CalibrateElbow2_Node_2 ---> [*] : (THIS^.Calibrated)
		state "fbEventHandler(TASK_FAILED)" as eInnerState_CalibrateElbow2_Node_3 
		state eInnerState_CalibrateElbow2_Node_4 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_CalibrateElbow2_Node_5 
	}
	}
	eInnerState_Idle ---> eInnerState_CalibrateAllButElbow1 : (bStartCalibration)
	eInnerState_Idle_Node_0 ---> eInnerState_Idle_Node_1 : (bStartCalibration)
	eInnerState_Idle_Node_1 ---> eInnerState_Idle_ERROR : (bStartCalibration)
	eInnerState_CalibrateAllButElbow1 ---> eInnerState_CalibrateAllButElbow2 : (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready)
	eInnerState_CalibrateAllButElbow1_Node_0 ---> eInnerState_CalibrateAllButElbow1_Node_1 : (NOT (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready))
	eInnerState_CalibrateAllButElbow1_Node_1 ---> eInnerState_CalibrateAllButElbow1_ERROR : (NOT (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready))
	eInnerState_CalibrateAllButElbow2 ---> eInnerState_CalibrateElbow1 : (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready)
	eInnerState_CalibrateAllButElbow2_Node_0 ---> eInnerState_CalibrateAllButElbow2_Node_1 : (NOT (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready))
	eInnerState_CalibrateAllButElbow2_Node_1 ---> eInnerState_CalibrateAllButElbow2_Node_2 : (fbJointSR.Failed)
	eInnerState_CalibrateAllButElbow2_Node_2 ---> eInnerState_CalibrateAllButElbow2_ERROR : (fbJointSR.Failed)
	eInnerState_CalibrateAllButElbow2_Node_0 ---> eInnerState_CalibrateAllButElbow2_Node_3 : (NOT (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready))
	eInnerState_CalibrateAllButElbow2_Node_3 ---> eInnerState_CalibrateAllButElbow2_Node_4 : (fbJointSY.Failed)
	eInnerState_CalibrateAllButElbow2_Node_4 ---> eInnerState_CalibrateAllButElbow2_ERROR : (fbJointSY.Failed)
	eInnerState_CalibrateAllButElbow2_Node_0 ---> eInnerState_CalibrateAllButElbow2_Node_5 : (NOT (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready))
	eInnerState_CalibrateAllButElbow2_Node_5 ---> eInnerState_CalibrateAllButElbow2_Node_6 : (fbJointG1.Failed)
	eInnerState_CalibrateAllButElbow2_Node_6 ---> eInnerState_CalibrateAllButElbow2_ERROR : (fbJointG1.Failed)
	eInnerState_CalibrateAllButElbow2_Node_0 ---> eInnerState_CalibrateAllButElbow2_Node_7 : (NOT (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready))
	eInnerState_CalibrateAllButElbow2_Node_7 ---> eInnerState_CalibrateAllButElbow2_Node_8 : (fbJointG2.Failed)
	eInnerState_CalibrateAllButElbow2_Node_8 ---> eInnerState_CalibrateAllButElbow2_ERROR : (fbJointG2.Failed)
	eInnerState_CalibrateAllButElbow2_Node_0 ---> eInnerState_CalibrateAllButElbow2_Node_9 : (NOT (fbJointSR.Ready\nAND fbJointSY.Ready\nAND fbJointG1.Ready\nAND fbJointG2.Ready\nAND fbJointG3.Ready))
	eInnerState_CalibrateAllButElbow2_Node_9 ---> eInnerState_CalibrateAllButElbow2_Node_10 : (fbJointG3.Failed)
	eInnerState_CalibrateAllButElbow2_Node_10 ---> eInnerState_CalibrateAllButElbow2_ERROR : (fbJointG3.Failed)
	eInnerState_CalibrateElbow1 ---> eInnerState_CalibrateElbow2 : (fbJointE.Ready)
	eInnerState_CalibrateElbow1_Node_0 ---> eInnerState_CalibrateElbow1_Node_1 : (NOT (fbJointE.Ready))
	eInnerState_CalibrateElbow1_Node_1 ---> eInnerState_CalibrateElbow1_ERROR : (NOT (fbJointE.Ready))
	eInnerState_CalibrateElbow2_Node_0 ---> eInnerState_CalibrateElbow2_Node_1 : (fbJointE.Ready)
	eInnerState_CalibrateElbow2_Node_1 ---> eInnerState_CalibrateElbow2_Node_2 : (THIS^.Calibrated)
	eInnerState_CalibrateElbow2 ---> eInnerState_Idle : (THIS^.Calibrated)
	eInnerState_CalibrateElbow2_Node_1 ---> eInnerState_CalibrateElbow2_Node_3 : (NOT (THIS^.Calibrated))
	eInnerState_CalibrateElbow2_Node_3 ---> eInnerState_CalibrateElbow2_ERROR : (NOT (THIS^.Calibrated))
	eInnerState_CalibrateElbow2_Node_0 ---> eInnerState_CalibrateElbow2_Node_4 : (NOT (fbJointE.Ready))
	eInnerState_CalibrateElbow2_Node_4 ---> eInnerState_CalibrateElbow2_Node_5 : (fbJointE.Failed)
	eInnerState_CalibrateElbow2_Node_5 ---> eInnerState_CalibrateElbow2_ERROR : (fbJointE.Failed)


}

@enduml
