@startuml State Diagram

!theme plain
'skin rose
'left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_Encoder State Diagram



state FB_Encoder{

state eInnerState #84b1f5 {
	[*] --> eInnerState_Idle : START
	state eInnerState_Idle #lightblue {
state "ERROR" as eInnerState_Idle_ERROR <<exitPoint>> #ff3333
	state eInnerState_Idle_Node_0 <<choice>>
	[*] ---> eInnerState_Idle_Node_0 : START
	eInnerState_Idle_Node_0 ---> [*] : (bStartCalibration)
		state eInnerState_Idle_Node_1 <<choice>>
	}
	state eInnerState_SetPositiveDirection #lightblue {
state "ERROR" as eInnerState_SetPositiveDirection_ERROR <<exitPoint>> #ff3333
	state "fbWriteBoolParameter()" as eInnerState_SetPositiveDirection_Node_0 
	[*] ---> eInnerState_SetPositiveDirection_Node_0 : START
		state eInnerState_SetPositiveDirection_Node_1 <<choice>>
		state "fbWriteBoolParameter()" as eInnerState_SetPositiveDirection_Node_2 
	eInnerState_SetPositiveDirection_Node_2 ---> [*] : (fbWriteBoolParameter.Done)
		state eInnerState_SetPositiveDirection_Node_3 <<choice>>
		state "fbEventHandler()" as eInnerState_SetPositiveDirection_Node_4 
	}
	state eInnerState_SetScaleDen #lightblue {
state "ERROR" as eInnerState_SetScaleDen_ERROR <<exitPoint>> #ff3333
	state eInnerState_SetScaleDen_Node_0 <<choice>>
	[*] ---> eInnerState_SetScaleDen_Node_0 : START
	state "fbWriteParameter()" as eInnerState_SetScaleDen_Node_1 
		state eInnerState_SetScaleDen_Node_2 <<choice>>
		state "fbWriteParameter()" as eInnerState_SetScaleDen_Node_3 
	eInnerState_SetScaleDen_Node_3 ---> [*] : (fbWriteParameter.Done)
		state eInnerState_SetScaleDen_Node_4 <<choice>>
		state "fbEventHandler()" as eInnerState_SetScaleDen_Node_5 
	state "fbEventHandler(INVALID_PARAMETER)" as eInnerState_SetScaleDen_Node_6 
	}
	state eInnerState_SetScaleNum #lightblue {
state "ERROR" as eInnerState_SetScaleNum_ERROR <<exitPoint>> #ff3333
	state eInnerState_SetScaleNum_Node_0 <<choice>>
	[*] ---> eInnerState_SetScaleNum_Node_0 : START
	state "fbWriteParameter()" as eInnerState_SetScaleNum_Node_1 
		state eInnerState_SetScaleNum_Node_2 <<choice>>
		state "fbWriteParameter()" as eInnerState_SetScaleNum_Node_3 
			state eInnerState_SetScaleNum_Node_4 <<choice>>
	eInnerState_SetScaleNum_Node_4 ---> [*] : (bIsAbsoluteEncoder)
	eInnerState_SetScaleNum_Node_4 ---> [*] : (NOT (bIsAbsoluteEncoder))
		state eInnerState_SetScaleNum_Node_5 <<choice>>
		state "fbEventHandler()" as eInnerState_SetScaleNum_Node_6 
	state "fbEventHandler(INVALID_PARAMETER)" as eInnerState_SetScaleNum_Node_7 
	}
	state eInnerState_SetAbsEncoderOffset1 #lightblue {
state "ERROR" as eInnerState_SetAbsEncoderOffset1_ERROR <<exitPoint>> #ff3333
	state "fbWriteParameter()" as eInnerState_SetAbsEncoderOffset1_Node_0 
	[*] ---> eInnerState_SetAbsEncoderOffset1_Node_0 : START
		state eInnerState_SetAbsEncoderOffset1_Node_1 <<choice>>
		state "fbWriteParameter()" as eInnerState_SetAbsEncoderOffset1_Node_2 
	eInnerState_SetAbsEncoderOffset1_Node_2 ---> [*] : (fbWriteParameter.Done)
		state eInnerState_SetAbsEncoderOffset1_Node_3 <<choice>>
		state "fbEventHandler()" as eInnerState_SetAbsEncoderOffset1_Node_4 
	}
	state eInnerState_SetAbsEncoderOffset2 #lightblue {
state "ERROR" as eInnerState_SetAbsEncoderOffset2_ERROR <<exitPoint>> #ff3333
	state "fbHome()" as eInnerState_SetAbsEncoderOffset2_Node_0 
	[*] ---> eInnerState_SetAbsEncoderOffset2_Node_0 : START
		state eInnerState_SetAbsEncoderOffset2_Node_1 <<choice>>
		state "fbHome()" as eInnerState_SetAbsEncoderOffset2_Node_2 
	eInnerState_SetAbsEncoderOffset2_Node_2 ---> [*] : (fbHome.Done)
		state eInnerState_SetAbsEncoderOffset2_Node_3 <<choice>>
		state "fbEventHandler()" as eInnerState_SetAbsEncoderOffset2_Node_4 
	}
	state eInnerState_SetIncEncoderHome #lightblue {
state "ERROR" as eInnerState_SetIncEncoderHome_ERROR <<exitPoint>> #ff3333
	state eInnerState_SetIncEncoderHome_Node_0 <<choice>>
	[*] ---> eInnerState_SetIncEncoderHome_Node_0 : START
	state "fbHome()" as eInnerState_SetIncEncoderHome_Node_1 
	state "fbHome()" as eInnerState_SetIncEncoderHome_Node_2 
		state eInnerState_SetIncEncoderHome_Node_3 <<choice>>
		state "fbHome()" as eInnerState_SetIncEncoderHome_Node_4 
	eInnerState_SetIncEncoderHome_Node_4 ---> [*] : (fbHome.Done)
		state eInnerState_SetIncEncoderHome_Node_5 <<choice>>
		state "fbEventHandler()" as eInnerState_SetIncEncoderHome_Node_6 
	}
	state eInnerState_WaitForStableOutput #lightblue {
state "ERROR" as eInnerState_WaitForStableOutput_ERROR <<exitPoint>> #ff3333
	state eInnerState_WaitForStableOutput_Node_0 <<choice>>
	[*] ---> eInnerState_WaitForStableOutput_Node_0 : START
	eInnerState_WaitForStableOutput_Node_0 ---> [*] : (nCounter > SystemConfig.nENCODER_FILTER_SAMPLES)
	}
	state eInnerState_VerifyAxis #lightblue {
state "ERROR" as eInnerState_VerifyAxis_ERROR <<exitPoint>> #ff3333
	state eInnerState_VerifyAxis_Node_0 <<choice>>
	[*] ---> eInnerState_VerifyAxis_Node_0 : START
	eInnerState_VerifyAxis_Node_0 ---> [*] : (NOT (UpdateAxis() = FALSE))
	}
	state eInnerState_WrapUpCalibration #lightblue {
state "ERROR" as eInnerState_WrapUpCalibration_ERROR <<exitPoint>> #ff3333
	}
	}
	eInnerState_Idle ---> eInnerState_SetPositiveDirection : (bStartCalibration)
	eInnerState_Idle_Node_0 ---> eInnerState_Idle_Node_1 : (bStartCalibration)
	eInnerState_Idle_Node_1 ---> eInnerState_Idle_ERROR : (bStartCalibration)
	eInnerState_SetPositiveDirection_Node_0 ---> eInnerState_SetPositiveDirection_Node_1
	eInnerState_SetPositiveDirection_Node_1 ---> eInnerState_SetPositiveDirection_Node_2 : (fbWriteBoolParameter.Done)
	eInnerState_SetPositiveDirection ---> eInnerState_SetScaleDen : (fbWriteBoolParameter.Done)
	eInnerState_SetPositiveDirection_Node_2 ---> eInnerState_SetPositiveDirection_Node_3 : (NOT (fbWriteBoolParameter.Done))
	eInnerState_SetPositiveDirection_Node_3 ---> eInnerState_SetPositiveDirection_Node_4 : (fbWriteBoolParameter.Error)
	eInnerState_SetPositiveDirection_Node_4 ---> eInnerState_SetPositiveDirection_ERROR : (fbWriteBoolParameter.Error)
	eInnerState_SetScaleDen_Node_0 ---> eInnerState_SetScaleDen_Node_1 : (stEncoderParams.fScaleDen > 0.1)
	eInnerState_SetScaleDen_Node_1 ---> eInnerState_SetScaleDen_Node_2 : (stEncoderParams.fScaleDen > 0.1)
	eInnerState_SetScaleDen_Node_2 ---> eInnerState_SetScaleDen_Node_3 : (fbWriteParameter.Done)
	eInnerState_SetScaleDen ---> eInnerState_SetScaleNum : (fbWriteParameter.Done)
	eInnerState_SetScaleDen_Node_3 ---> eInnerState_SetScaleDen_Node_4 : (NOT (fbWriteParameter.Done))
	eInnerState_SetScaleDen_Node_4 ---> eInnerState_SetScaleDen_Node_5 : (fbWriteParameter.Error)
	eInnerState_SetScaleDen_Node_5 ---> eInnerState_SetScaleDen_ERROR : (fbWriteParameter.Error)
	eInnerState_SetScaleDen_Node_0 ---> eInnerState_SetScaleDen_Node_6 : (NOT (stEncoderParams.fScaleDen > 0.1))
	eInnerState_SetScaleDen_Node_6 ---> eInnerState_SetScaleDen_ERROR : (NOT (stEncoderParams.fScaleDen > 0.1))
	eInnerState_SetScaleNum_Node_0 ---> eInnerState_SetScaleNum_Node_1 : (stEncoderParams.fScaleNum > 0)
	eInnerState_SetScaleNum_Node_1 ---> eInnerState_SetScaleNum_Node_2 : (stEncoderParams.fScaleNum > 0)
	eInnerState_SetScaleNum_Node_2 ---> eInnerState_SetScaleNum_Node_3 : (fbWriteParameter.Done)
	eInnerState_SetScaleNum_Node_3 ---> eInnerState_SetScaleNum_Node_4 : (fbWriteParameter.Done)
	eInnerState_SetScaleNum ---> eInnerState_SetAbsEncoderOffset1 : (bIsAbsoluteEncoder)
	eInnerState_SetScaleNum ---> eInnerState_SetIncEncoderHome : (NOT (bIsAbsoluteEncoder))
	eInnerState_SetScaleNum_Node_3 ---> eInnerState_SetScaleNum_Node_5 : (NOT (fbWriteParameter.Done))
	eInnerState_SetScaleNum_Node_5 ---> eInnerState_SetScaleNum_Node_6 : (fbWriteParameter.Error)
	eInnerState_SetScaleNum_Node_6 ---> eInnerState_SetScaleNum_ERROR : (fbWriteParameter.Error)
	eInnerState_SetScaleNum_Node_0 ---> eInnerState_SetScaleNum_Node_7 : (NOT (stEncoderParams.fScaleNum > 0))
	eInnerState_SetScaleNum_Node_7 ---> eInnerState_SetScaleNum_ERROR : (NOT (stEncoderParams.fScaleNum > 0))
	eInnerState_SetAbsEncoderOffset1_Node_0 ---> eInnerState_SetAbsEncoderOffset1_Node_1
	eInnerState_SetAbsEncoderOffset1_Node_1 ---> eInnerState_SetAbsEncoderOffset1_Node_2 : (fbWriteParameter.Done)
	eInnerState_SetAbsEncoderOffset1 ---> eInnerState_SetAbsEncoderOffset2 : (fbWriteParameter.Done)
	eInnerState_SetAbsEncoderOffset1_Node_2 ---> eInnerState_SetAbsEncoderOffset1_Node_3 : (NOT (fbWriteParameter.Done))
	eInnerState_SetAbsEncoderOffset1_Node_3 ---> eInnerState_SetAbsEncoderOffset1_Node_4 : (fbWriteParameter.Error)
	eInnerState_SetAbsEncoderOffset1_Node_4 ---> eInnerState_SetAbsEncoderOffset1_ERROR : (fbWriteParameter.Error)
	eInnerState_SetAbsEncoderOffset2_Node_0 ---> eInnerState_SetAbsEncoderOffset2_Node_1
	eInnerState_SetAbsEncoderOffset2_Node_1 ---> eInnerState_SetAbsEncoderOffset2_Node_2 : (fbHome.Done)
	eInnerState_SetAbsEncoderOffset2 ---> eInnerState_VerifyAxis : (fbHome.Done)
	eInnerState_SetAbsEncoderOffset2_Node_2 ---> eInnerState_SetAbsEncoderOffset2_Node_3 : (NOT (fbHome.Done))
	eInnerState_SetAbsEncoderOffset2_Node_3 ---> eInnerState_SetAbsEncoderOffset2_Node_4 : (fbHome.Error)
	eInnerState_SetAbsEncoderOffset2_Node_4 ---> eInnerState_SetAbsEncoderOffset2_ERROR : (fbHome.Error)
	eInnerState_SetIncEncoderHome_Node_0 ---> eInnerState_SetIncEncoderHome_Node_1 : (bHomePositionOverride)
	eInnerState_SetIncEncoderHome_Node_0 ---> eInnerState_SetIncEncoderHome_Node_2 : (NOT (bHomePositionOverride))
	eInnerState_SetIncEncoderHome_Node_0 ---> eInnerState_SetIncEncoderHome_Node_3 : (NOT (bHomePositionOverride))
	eInnerState_SetIncEncoderHome_Node_3 ---> eInnerState_SetIncEncoderHome_Node_4 : (fbHome.Done)
	eInnerState_SetIncEncoderHome ---> eInnerState_WaitForStableOutput : (fbHome.Done)
	eInnerState_SetIncEncoderHome_Node_4 ---> eInnerState_SetIncEncoderHome_Node_5 : (NOT (fbHome.Done))
	eInnerState_SetIncEncoderHome_Node_5 ---> eInnerState_SetIncEncoderHome_Node_6 : (fbHome.Error)
	eInnerState_SetIncEncoderHome_Node_6 ---> eInnerState_SetIncEncoderHome_ERROR : (fbHome.Error)
	eInnerState_WaitForStableOutput ---> eInnerState_VerifyAxis : (nCounter > SystemConfig.nENCODER_FILTER_SAMPLES)
	eInnerState_VerifyAxis ---> eInnerState_WrapUpCalibration : (NOT (UpdateAxis() = FALSE))


}

@enduml
