@startuml State Diagram

!theme plain
'skin rose
'left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_LinearActuator State Diagram



state FB_LinearActuator{

state eInnerState #84b1f5 {
	[*] --> eInnerState_Idle : START
	state eInnerState_Idle #lightblue {
state "ERROR" as eInnerState_Idle_ERROR <<exitPoint>> #ff3333
	state eInnerState_Idle_Node_0 <<choice>>
	[*] ---> eInnerState_Idle_Node_0 : START
		state eInnerState_Idle_Node_1 <<choice>>
	eInnerState_Idle_Node_1 ---> [*] : (Enabled)
	state eInnerState_Idle_Node_2 <<choice>>
	eInnerState_Idle_Node_2 ---> [*] : (bStartHoming)
	state eInnerState_Idle_Node_3 <<choice>>
	eInnerState_Idle_Node_3 ---> [*] : (bStartJogging)
	}
	state eInnerState_Homing1 #lightblue {
state "ERROR" as eInnerState_Homing1_ERROR <<exitPoint>> #ff3333
	state eInnerState_Homing1_Node_0 <<choice>>
	[*] ---> eInnerState_Homing1_Node_0 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_Homing1_Node_1 
		state eInnerState_Homing1_Node_2 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_Homing1_Node_3 
	eInnerState_Homing1_Node_2 ---> [*] : (NOT (fbHoming.bError))
	}
	state eInnerState_Homing2 #lightblue {
state "ERROR" as eInnerState_Homing2_ERROR <<exitPoint>> #ff3333
	state "fbPower()" as eInnerState_Homing2_Node_0 
	[*] ---> eInnerState_Homing2_Node_0 : START
	state "fbReset()" as eInnerState_Homing2_Node_1 
	state "fbJog()" as eInnerState_Homing2_Node_2 
		state eInnerState_Homing2_Node_3 <<choice>>
			state eInnerState_Homing2_Node_4 <<choice>>
			state "fbEventHandler(TASK_FAILED)" as eInnerState_Homing2_Node_5 
				state eInnerState_Homing2_Node_6 <<choice>>
				state "fbEventHandler(REQUEST_COMPLETED)" as eInnerState_Homing2_Node_7 
	eInnerState_Homing2_Node_7 ---> [*] : (Homed)
				state "fbEventHandler(TASK_FAILED)" as eInnerState_Homing2_Node_8 
	}
	state eInnerState_Jogging1 #lightblue {
state "ERROR" as eInnerState_Jogging1_ERROR <<exitPoint>> #ff3333
	state eInnerState_Jogging1_Node_0 <<choice>>
	[*] ---> eInnerState_Jogging1_Node_0 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_Jogging1_Node_1 
		state eInnerState_Jogging1_Node_2 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_Jogging1_Node_3 
	eInnerState_Jogging1_Node_2 ---> [*] : (NOT (fbJogging.bError))
	}
	state eInnerState_Jogging2 #lightblue {
state "ERROR" as eInnerState_Jogging2_ERROR <<exitPoint>> #ff3333
	state "fbPower()" as eInnerState_Jogging2_Node_0 
	[*] ---> eInnerState_Jogging2_Node_0 : START
	state "fbReset()" as eInnerState_Jogging2_Node_1 
	state "fbJog()" as eInnerState_Jogging2_Node_2 
		state eInnerState_Jogging2_Node_3 <<choice>>
			state eInnerState_Jogging2_Node_4 <<choice>>
			state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_Jogging2_Node_5 
	eInnerState_Jogging2_Node_4 ---> [*] : (NOT (fbJogging.bError))
	}
	state eInnerState_MovingAbs #lightblue {
state "ERROR" as eInnerState_MovingAbs_ERROR <<exitPoint>> #ff3333
	}
	state eInnerState_Disabling1 #lightblue {
state "ERROR" as eInnerState_Disabling1_ERROR <<exitPoint>> #ff3333
	state eInnerState_Disabling1_Node_0 <<choice>>
	[*] ---> eInnerState_Disabling1_Node_0 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_Disabling1_Node_1 
		state eInnerState_Disabling1_Node_2 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_Disabling1_Node_3 
	eInnerState_Disabling1_Node_2 ---> [*] : (NOT (fbEnable.bError))
	}
	state eInnerState_Disabling2 #lightblue {
state "ERROR" as eInnerState_Disabling2_ERROR <<exitPoint>> #ff3333
	state "fbPower()" as eInnerState_Disabling2_Node_0 
	[*] ---> eInnerState_Disabling2_Node_0 : START
		state eInnerState_Disabling2_Node_1 <<choice>>
			state eInnerState_Disabling2_Node_2 <<choice>>
			state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_Disabling2_Node_3 
			state eInnerState_Disabling2_Node_4 <<choice>>
	eInnerState_Disabling2_Node_4 ---> [*] : (Enabled=FALSE)
			state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_Disabling2_Node_5 
	}
	}
	eInnerState_Idle_Node_0 ---> eInnerState_Idle_Node_1 : (bEnableAxis=FALSE)
	eInnerState_Idle ---> eInnerState_Disabling1 : (Enabled)
	eInnerState_Idle_Node_0 ---> eInnerState_Idle_Node_2 : (NOT (bEnableAxis=FALSE))
	eInnerState_Idle ---> eInnerState_Homing1 : (bStartHoming)
	eInnerState_Idle_Node_2 ---> eInnerState_Idle_Node_3 : (NOT (bStartHoming))
	eInnerState_Idle ---> eInnerState_Jogging1 : (bStartJogging)
	eInnerState_Homing1_Node_0 ---> eInnerState_Homing1_Node_1 : (fbHoming.Busy)
	eInnerState_Homing1_Node_1 ---> eInnerState_Homing1_ERROR : (fbHoming.Busy)
	eInnerState_Homing1_Node_0 ---> eInnerState_Homing1_Node_2 : (NOT (fbHoming.Busy))
	eInnerState_Homing1_Node_2 ---> eInnerState_Homing1_Node_3 : (fbHoming.bError)
	eInnerState_Homing1_Node_3 ---> eInnerState_Homing1_ERROR : (fbHoming.bError)
	eInnerState_Homing1 ---> eInnerState_Homing2 : (NOT (fbHoming.bError))
	eInnerState_Homing2_Node_0 ---> eInnerState_Homing2_Node_1
	eInnerState_Homing2_Node_1 ---> eInnerState_Homing2_Node_2
	eInnerState_Homing2_Node_2 ---> eInnerState_Homing2_Node_3
	eInnerState_Homing2_Node_3 ---> eInnerState_Homing2_Node_4 : (NOT (fbHoming.Busy))
	eInnerState_Homing2_Node_4 ---> eInnerState_Homing2_Node_5 : (fbHoming.bError)
	eInnerState_Homing2_Node_5 ---> eInnerState_Homing2_ERROR : (fbHoming.bError)
	eInnerState_Homing2_Node_4 ---> eInnerState_Homing2_Node_6 : (NOT (fbHoming.bError))
	eInnerState_Homing2_Node_6 ---> eInnerState_Homing2_Node_7 : (Homed)
	eInnerState_Homing2 ---> eInnerState_Idle : (Homed)
	eInnerState_Homing2_Node_6 ---> eInnerState_Homing2_Node_8 : (NOT (Homed))
	eInnerState_Homing2_Node_8 ---> eInnerState_Homing2_ERROR : (NOT (Homed))
	eInnerState_Jogging1_Node_0 ---> eInnerState_Jogging1_Node_1 : (fbJogging.Busy)
	eInnerState_Jogging1_Node_1 ---> eInnerState_Jogging1_ERROR : (fbJogging.Busy)
	eInnerState_Jogging1_Node_0 ---> eInnerState_Jogging1_Node_2 : (NOT (fbJogging.Busy))
	eInnerState_Jogging1_Node_2 ---> eInnerState_Jogging1_Node_3 : (fbJogging.bError)
	eInnerState_Jogging1_Node_3 ---> eInnerState_Jogging1_ERROR : (fbJogging.bError)
	eInnerState_Jogging1 ---> eInnerState_Homing2 : (NOT (fbJogging.bError))
	eInnerState_Jogging2_Node_0 ---> eInnerState_Jogging2_Node_1
	eInnerState_Jogging2_Node_1 ---> eInnerState_Jogging2_Node_2
	eInnerState_Jogging2_Node_2 ---> eInnerState_Jogging2_Node_3
	eInnerState_Jogging2_Node_3 ---> eInnerState_Jogging2_Node_4 : (NOT (fbJogging.Busy))
	eInnerState_Jogging2_Node_4 ---> eInnerState_Jogging2_Node_5 : (fbJogging.bError)
	eInnerState_Jogging2_Node_5 ---> eInnerState_Jogging2_ERROR : (fbJogging.bError)
	eInnerState_Jogging2 ---> eInnerState_Idle : (NOT (fbJogging.bError))
	eInnerState_Disabling1_Node_0 ---> eInnerState_Disabling1_Node_1 : (fbEnable.Busy)
	eInnerState_Disabling1_Node_1 ---> eInnerState_Disabling1_ERROR : (fbEnable.Busy)
	eInnerState_Disabling1_Node_0 ---> eInnerState_Disabling1_Node_2 : (NOT (fbEnable.Busy))
	eInnerState_Disabling1_Node_2 ---> eInnerState_Disabling1_Node_3 : (fbEnable.bError)
	eInnerState_Disabling1_Node_3 ---> eInnerState_Disabling1_ERROR : (fbEnable.bError)
	eInnerState_Disabling1 ---> eInnerState_Disabling2 : (NOT (fbEnable.bError))
	eInnerState_Disabling2_Node_0 ---> eInnerState_Disabling2_Node_1
	eInnerState_Disabling2_Node_1 ---> eInnerState_Disabling2_Node_2 : (NOT (fbEnable.Busy))
	eInnerState_Disabling2_Node_2 ---> eInnerState_Disabling2_Node_3 : (fbEnable.bError)
	eInnerState_Disabling2_Node_3 ---> eInnerState_Disabling2_ERROR : (fbEnable.bError)
	eInnerState_Disabling2_Node_3 ---> eInnerState_Disabling2_Node_4 : (NOT (fbEnable.bError))
	eInnerState_Disabling2 ---> eInnerState_Idle : (Enabled=FALSE)
	eInnerState_Disabling2_Node_4 ---> eInnerState_Disabling2_Node_5 : (NOT (Enabled=FALSE))
	eInnerState_Disabling2_Node_5 ---> eInnerState_Disabling2_ERROR : (NOT (Enabled=FALSE))


}

@enduml
