@startuml State Diagram

!theme plain
'skin rose
'left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_StateMachine State Diagram



state FB_StateMachine{

state eOuterLoopState #84b1f5 {
	[*] --> eOuterLoopState_Setup : START
	state eOuterLoopState_Setup #lightblue {
state "ERROR" as eOuterLoopState_Setup_ERROR <<exitPoint>> #ff3333
	state "Setup_0()" as eOuterLoopState_Setup_Node_0 
	[*] ---> eOuterLoopState_Setup_Node_0 : START
	state "Setup()" as eOuterLoopState_Setup_Node_1 
		state eOuterLoopState_Setup_Node_2 <<choice>>
		state "Reset()" as eOuterLoopState_Setup_Node_3 
	eOuterLoopState_Setup_Node_3 ---> [*] : (bActive)
	eOuterLoopState_Setup_Node_2 ---> [*] : (NOT (bActive))
	}
	state eOuterLoopState_Operational #lightblue {
state "ERROR" as eOuterLoopState_Operational_ERROR <<exitPoint>> #ff3333
	state "ReadStatus()" as eOuterLoopState_Operational_Node_0 
	[*] ---> eOuterLoopState_Operational_Node_0 : START
		state eOuterLoopState_Operational_Node_1 <<choice>>
			state eOuterLoopState_Operational_Node_2 <<choice>>
	eOuterLoopState_Operational_Node_2 ---> [*] : (Disable())
	eOuterLoopState_Operational_Node_2 ---> [*] : (NOT (Disable()))
		state eOuterLoopState_Operational_Node_3 <<choice>>
		state "InnerLoopSM()" as eOuterLoopState_Operational_Node_4 
			state eOuterLoopState_Operational_Node_5 <<choice>>
	eOuterLoopState_Operational_Node_5 ---> [*] : (Disable())
	eOuterLoopState_Operational_Node_5 ---> [*] : (NOT (Disable()))
	}
	state eOuterLoopState_DisablingInactive #lightblue {
state "ERROR" as eOuterLoopState_DisablingInactive_ERROR <<exitPoint>> #ff3333
	state eOuterLoopState_DisablingInactive_Node_0 <<choice>>
	[*] ---> eOuterLoopState_DisablingInactive_Node_0 : START
	eOuterLoopState_DisablingInactive_Node_0 ---> [*] : (Disable())
	}
	state eOuterLoopState_Inactive #lightblue {
state "ERROR" as eOuterLoopState_Inactive_ERROR <<exitPoint>> #ff3333
	state eOuterLoopState_Inactive_Node_0 <<choice>>
	[*] ---> eOuterLoopState_Inactive_Node_0 : START
	state "Reset()" as eOuterLoopState_Inactive_Node_1 
	eOuterLoopState_Inactive_Node_1 ---> [*] : (bActive)
	}
	state eOuterLoopState_DisablingError #lightblue {
state "ERROR" as eOuterLoopState_DisablingError_ERROR <<exitPoint>> #ff3333
	state eOuterLoopState_DisablingError_Node_0 <<choice>>
	[*] ---> eOuterLoopState_DisablingError_Node_0 : START
	eOuterLoopState_DisablingError_Node_0 ---> [*] : (Disable())
	}
	state eOuterLoopState_DisabledError #lightblue {
state "ERROR" as eOuterLoopState_DisabledError_ERROR <<exitPoint>> #ff3333
	state eOuterLoopState_DisabledError_Node_0 <<choice>>
	[*] ---> eOuterLoopState_DisabledError_Node_0 : START
	eOuterLoopState_DisabledError_Node_0 ---> [*] : (bErrorAck)
	}
	}
	eOuterLoopState_Setup_Node_0 ---> eOuterLoopState_Setup_Node_1
	eOuterLoopState_Setup_Node_1 ---> eOuterLoopState_Setup_Node_2
	eOuterLoopState_Setup_Node_2 ---> eOuterLoopState_Setup_Node_3 : (bActive)
	eOuterLoopState_Setup ---> eOuterLoopState_Operational : (bActive)
	eOuterLoopState_Setup ---> eOuterLoopState_Inactive : (NOT (bActive))
	eOuterLoopState_Operational_Node_0 ---> eOuterLoopState_Operational_Node_1
	eOuterLoopState_Operational_Node_1 ---> eOuterLoopState_Operational_Node_2 : (bError)
	eOuterLoopState_Operational ---> eOuterLoopState_DisabledError : (Disable())
	eOuterLoopState_Operational ---> eOuterLoopState_DisablingError : (NOT (Disable()))
	eOuterLoopState_Operational_Node_1 ---> eOuterLoopState_Operational_Node_3 : (NOT (bError))
	eOuterLoopState_Operational_Node_3 ---> eOuterLoopState_Operational_Node_4 : (bActive)
	eOuterLoopState_Operational_Node_3 ---> eOuterLoopState_Operational_Node_5 : (NOT (bActive))
	eOuterLoopState_Operational ---> eOuterLoopState_Inactive : (Disable())
	eOuterLoopState_Operational ---> eOuterLoopState_DisablingInactive : (NOT (Disable()))
	eOuterLoopState_DisablingInactive ---> eOuterLoopState_Inactive : (Disable())
	eOuterLoopState_Inactive_Node_0 ---> eOuterLoopState_Inactive_Node_1 : (bActive)
	eOuterLoopState_Inactive ---> eOuterLoopState_Operational : (bActive)
	eOuterLoopState_DisablingError ---> eOuterLoopState_DisabledError : (Disable())
	eOuterLoopState_DisabledError ---> eOuterLoopState_Inactive : (bErrorAck)


}

@enduml
