@startuml State Diagram

!theme plain
'skin rose
'left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_Teleoperation State Diagram



state FB_Teleoperation{

state eInnerState #84b1f5 {
	[*] --> eInnerState_Idle : START
	state eInnerState_Idle #lightblue {
state "ERROR" as eInnerState_Idle_ERROR <<exitPoint>> #ff3333
	state eInnerState_Idle_Node_0 <<choice>>
	[*] ---> eInnerState_Idle_Node_0 : START
	eInnerState_Idle_Node_0 ---> [*] : (bStart)
	}
	state eInnerState_StartCommRM1 #lightblue {
state "ERROR" as eInnerState_StartCommRM1_ERROR <<exitPoint>> #ff3333
	state eInnerState_StartCommRM1_Node_0 <<choice>>
	[*] ---> eInnerState_StartCommRM1_Node_0 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_StartCommRM1_Node_1 
		state eInnerState_StartCommRM1_Node_2 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_StartCommRM1_Node_3 
	eInnerState_StartCommRM1_Node_2 ---> [*] : (NOT (fbRemoteManipulator.bError))
	}
	state eInnerState_StartCommRM2 #lightblue {
state "ERROR" as eInnerState_StartCommRM2_ERROR <<exitPoint>> #ff3333
	state eInnerState_StartCommRM2_Node_0 <<choice>>
	[*] ---> eInnerState_StartCommRM2_Node_0 : START
		state eInnerState_StartCommRM2_Node_1 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_StartCommRM2_Node_2 
	eInnerState_StartCommRM2_Node_1 ---> [*] : (NOT (fbRemoteManipulator.bError))
	}
	state eInnerState_EnableArmMotors1 #lightblue {
state "ERROR" as eInnerState_EnableArmMotors1_ERROR <<exitPoint>> #ff3333
	state eInnerState_EnableArmMotors1_Node_0 <<choice>>
	[*] ---> eInnerState_EnableArmMotors1_Node_0 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_EnableArmMotors1_Node_1 
		state eInnerState_EnableArmMotors1_Node_2 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_EnableArmMotors1_Node_3 
	eInnerState_EnableArmMotors1_Node_2 ---> [*] : (NOT (fbArmMotors.bError))
	}
	state eInnerState_EnableArmMotors2 #lightblue {
state "ERROR" as eInnerState_EnableArmMotors2_ERROR <<exitPoint>> #ff3333
	state eInnerState_EnableArmMotors2_Node_0 <<choice>>
	[*] ---> eInnerState_EnableArmMotors2_Node_0 : START
		state eInnerState_EnableArmMotors2_Node_1 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_EnableArmMotors2_Node_2 
	eInnerState_EnableArmMotors2_Node_1 ---> [*] : (NOT (fbArmMotors.bError))
	}
	state eInnerState_Setup #lightblue {
state "ERROR" as eInnerState_Setup_ERROR <<exitPoint>> #ff3333
	}
	state eInnerState_Active #lightblue {
state "ERROR" as eInnerState_Active_ERROR <<exitPoint>> #ff3333
	}
	state eInnerState_WrapUp #lightblue {
state "ERROR" as eInnerState_WrapUp_ERROR <<exitPoint>> #ff3333
	}
	}
	eInnerState_Idle ---> eInnerState_StartCommRM1 : (bStart)
	eInnerState_StartCommRM1_Node_0 ---> eInnerState_StartCommRM1_Node_1 : (fbRemoteManipulator.Busy)
	eInnerState_StartCommRM1_Node_1 ---> eInnerState_StartCommRM1_ERROR : (fbRemoteManipulator.Busy)
	eInnerState_StartCommRM1_Node_0 ---> eInnerState_StartCommRM1_Node_2 : (NOT (fbRemoteManipulator.Busy))
	eInnerState_StartCommRM1_Node_2 ---> eInnerState_StartCommRM1_Node_3 : (fbRemoteManipulator.bError)
	eInnerState_StartCommRM1_Node_3 ---> eInnerState_StartCommRM1_ERROR : (fbRemoteManipulator.bError)
	eInnerState_StartCommRM1 ---> eInnerState_StartCommRM2 : (NOT (fbRemoteManipulator.bError))
	eInnerState_StartCommRM2_Node_0 ---> eInnerState_StartCommRM2_Node_1 : (NOT (fbRemoteManipulator.Busy))
	eInnerState_StartCommRM2_Node_1 ---> eInnerState_StartCommRM2_Node_2 : (fbRemoteManipulator.bError)
	eInnerState_StartCommRM2_Node_2 ---> eInnerState_StartCommRM2_ERROR : (fbRemoteManipulator.bError)
	eInnerState_StartCommRM2 ---> eInnerState_EnableArmMotors1 : (NOT (fbRemoteManipulator.bError))
	eInnerState_EnableArmMotors1_Node_0 ---> eInnerState_EnableArmMotors1_Node_1 : (fbArmMotors.Busy)
	eInnerState_EnableArmMotors1_Node_1 ---> eInnerState_EnableArmMotors1_ERROR : (fbArmMotors.Busy)
	eInnerState_EnableArmMotors1_Node_0 ---> eInnerState_EnableArmMotors1_Node_2 : (NOT (fbArmMotors.Busy))
	eInnerState_EnableArmMotors1_Node_2 ---> eInnerState_EnableArmMotors1_Node_3 : (fbArmMotors.bError)
	eInnerState_EnableArmMotors1_Node_3 ---> eInnerState_EnableArmMotors1_ERROR : (fbArmMotors.bError)
	eInnerState_EnableArmMotors1 ---> eInnerState_EnableArmMotors2 : (NOT (fbArmMotors.bError))
	eInnerState_EnableArmMotors2_Node_0 ---> eInnerState_EnableArmMotors2_Node_1 : (NOT (fbArmMotors.Busy))
	eInnerState_EnableArmMotors2_Node_1 ---> eInnerState_EnableArmMotors2_Node_2 : (fbArmMotors.bError)
	eInnerState_EnableArmMotors2_Node_2 ---> eInnerState_EnableArmMotors2_ERROR : (fbArmMotors.bError)
	eInnerState_EnableArmMotors2 ---> eInnerState_Setup : (NOT (fbArmMotors.bError))


}

@enduml
