@startuml State Diagram

!theme plain
'skin rose
'left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_Differentiator State Diagram



state FB_Differentiator{



}

@enduml
