@startuml State Diagram

!theme plain
'skin rose
'left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_NcAxisEnable State Diagram



state FB_NcAxisEnable{

state eInnerState #84b1f5 {
	[*] --> eInnerState_Idle : START
	state eInnerState_Idle #lightblue {
state "ERROR" as eInnerState_Idle_ERROR <<exitPoint>> #ff3333
	state eInnerState_Idle_Node_0 <<choice>>
	[*] ---> eInnerState_Idle_Node_0 : START
		state eInnerState_Idle_Node_1 <<choice>>
	eInnerState_Idle_Node_1 ---> [*] : (bEnable)
	eInnerState_Idle_Node_1 ---> [*] : (NOT (bEnable))
	}
	state eInnerState_CheckIfEnabled #lightblue {
state "ERROR" as eInnerState_CheckIfEnabled_ERROR <<exitPoint>> #ff3333
	[*] ---> [*]
	}
	state eInnerState_ResetAxis1 #lightblue {
state "ERROR" as eInnerState_ResetAxis1_ERROR <<exitPoint>> #ff3333
	state "fbReset()" as eInnerState_ResetAxis1_Node_0 
	[*] ---> eInnerState_ResetAxis1_Node_0 : START
	eInnerState_ResetAxis1_Node_0 ---> [*] : None
	}
	state eInnerState_ResetAxis2 #lightblue {
state "ERROR" as eInnerState_ResetAxis2_ERROR <<exitPoint>> #ff3333
	state eInnerState_ResetAxis2_Node_0 <<choice>>
	[*] ---> eInnerState_ResetAxis2_Node_0 : START
	state "fbReset()" as eInnerState_ResetAxis2_Node_1 
		state eInnerState_ResetAxis2_Node_2 <<choice>>
	eInnerState_ResetAxis2_Node_2 ---> [*] : (Enabled)
	eInnerState_ResetAxis2_Node_2 ---> [*] : (NOT (Enabled))
	state eInnerState_ResetAxis2_Node_3 <<choice>>
	state "fbEventHandler()" as eInnerState_ResetAxis2_Node_4 
		state eInnerState_ResetAxis2_Node_5 <<choice>>
		state "fbEventHandler(RESET_NOT_DONE_IN_ALLOTED_TIME)" as eInnerState_ResetAxis2_Node_6 
	}
	state eInnerState_EnableAxis1 #lightblue {
state "ERROR" as eInnerState_EnableAxis1_ERROR <<exitPoint>> #ff3333
	state "fbPower()" as eInnerState_EnableAxis1_Node_0 
	[*] ---> eInnerState_EnableAxis1_Node_0 : START
	eInnerState_EnableAxis1_Node_0 ---> [*] : None
	}
	state eInnerState_EnableAxis2 #lightblue {
state "ERROR" as eInnerState_EnableAxis2_ERROR <<exitPoint>> #ff3333
	state eInnerState_EnableAxis2_Node_0 <<choice>>
	[*] ---> eInnerState_EnableAxis2_Node_0 : START
	state "fbEventHandler()" as eInnerState_EnableAxis2_Node_1 
	state eInnerState_EnableAxis2_Node_2 <<choice>>
	state "fbReset()" as eInnerState_EnableAxis2_Node_3 
	eInnerState_EnableAxis2_Node_3 ---> [*] : (fbPower.Status = TRUE)
		state eInnerState_EnableAxis2_Node_4 <<choice>>
		state "fbEventHandler(ENABLE_NOT_DONE_IN_ALLOTED_TIME)" as eInnerState_EnableAxis2_Node_5 
	}
	state eInnerState_DisableAxis #lightblue {
state "ERROR" as eInnerState_DisableAxis_ERROR <<exitPoint>> #ff3333
	state "fbPower()" as eInnerState_DisableAxis_Node_0 
	[*] ---> eInnerState_DisableAxis_Node_0 : START
		state eInnerState_DisableAxis_Node_1 <<choice>>
		state "fbEventHandler()" as eInnerState_DisableAxis_Node_2 
		state eInnerState_DisableAxis_Node_3 <<choice>>
	eInnerState_DisableAxis_Node_3 ---> [*] : (fbPower.Status = FALSE)
	}
	}
	eInnerState_Idle_Node_0 ---> eInnerState_Idle_Node_1 : (bStart)
	eInnerState_Idle ---> eInnerState_CheckIfEnabled : (bEnable)
	eInnerState_Idle ---> eInnerState_DisableAxis : (NOT (bEnable))
	eInnerState_CheckIfEnabled ---> eInnerState_ResetAxis1
	eInnerState_ResetAxis1 ---> eInnerState_ResetAxis2 : None
	eInnerState_ResetAxis2_Node_0 ---> eInnerState_ResetAxis2_Node_1 : (fbReset.Done)
	eInnerState_ResetAxis2_Node_1 ---> eInnerState_ResetAxis2_Node_2 : (fbReset.Done)
	eInnerState_ResetAxis2 ---> eInnerState_Idle : (Enabled)
	eInnerState_ResetAxis2 ---> eInnerState_EnableAxis1 : (NOT (Enabled))
	eInnerState_ResetAxis2_Node_1 ---> eInnerState_ResetAxis2_Node_3 : (NOT (fbReset.Done))
	eInnerState_ResetAxis2_Node_3 ---> eInnerState_ResetAxis2_Node_4 : (fbReset.Error)
	eInnerState_ResetAxis2_Node_4 ---> eInnerState_ResetAxis2_ERROR : (fbReset.Error)
	eInnerState_ResetAxis2_Node_3 ---> eInnerState_ResetAxis2_Node_5 : (NOT (fbReset.Error))
	eInnerState_ResetAxis2_Node_5 ---> eInnerState_ResetAxis2_Node_6 : (nPLC_Cycles > SystemConfig.nSTEPPER_MAX_CYCLES_TO_RESET)
	eInnerState_ResetAxis2_Node_6 ---> eInnerState_ResetAxis2_ERROR : (nPLC_Cycles > SystemConfig.nSTEPPER_MAX_CYCLES_TO_RESET)
	eInnerState_EnableAxis1 ---> eInnerState_EnableAxis2 : None
	eInnerState_EnableAxis2_Node_0 ---> eInnerState_EnableAxis2_Node_1 : (fbPower.Error)
	eInnerState_EnableAxis2_Node_1 ---> eInnerState_EnableAxis2_ERROR : (fbPower.Error)
	eInnerState_EnableAxis2_Node_1 ---> eInnerState_EnableAxis2_Node_2 : (NOT (fbPower.Error))
	eInnerState_EnableAxis2_Node_2 ---> eInnerState_EnableAxis2_Node_3 : (fbPower.Status = TRUE)
	eInnerState_EnableAxis2 ---> eInnerState_Idle : (fbPower.Status = TRUE)
	eInnerState_EnableAxis2_Node_2 ---> eInnerState_EnableAxis2_Node_4 : (NOT (fbPower.Status = TRUE))
	eInnerState_EnableAxis2_Node_4 ---> eInnerState_EnableAxis2_Node_5 : (nPLC_Cycles > SystemConfig.nSTEPPER_MAX_CYCLES_TO_ENABLE)
	eInnerState_EnableAxis2_Node_5 ---> eInnerState_EnableAxis2_ERROR : (nPLC_Cycles > SystemConfig.nSTEPPER_MAX_CYCLES_TO_ENABLE)
	eInnerState_DisableAxis_Node_0 ---> eInnerState_DisableAxis_Node_1
	eInnerState_DisableAxis_Node_1 ---> eInnerState_DisableAxis_Node_2 : (fbPower.Error)
	eInnerState_DisableAxis_Node_2 ---> eInnerState_DisableAxis_ERROR : (fbPower.Error)
	eInnerState_DisableAxis_Node_2 ---> eInnerState_DisableAxis_Node_3 : (NOT (fbPower.Error))
	eInnerState_DisableAxis ---> eInnerState_Idle : (fbPower.Status = FALSE)
eInnerState : fbPower(Axis:=stParentAxisRef);\nfbReset(Axis:=stParentAxisRef);\n
eInnerState : 


}

@enduml
