@startuml State Diagram

!theme plain
'skin rose
'left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_NeuroArmPlusInvStaticsV2 State Diagram



state FB_NeuroArmPlusInvStaticsV2{



}

@enduml
