@startuml State Diagram

!theme plain
'skin rose
left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_SelfTest State Diagram



state FB_SelfTest{

state eInnerState #84b1f5 {
	[*] --> eInnerState_Idle : START
	state eInnerState_Idle #lightblue {
state "ERROR" as eInnerState_Idle_ERROR <<exitPoint>> #ff3333
	state eInnerState_Idle_Node_0 <<choice>>
	[*] ---> eInnerState_Idle_Node_0 : START
	eInnerState_Idle_Node_0 ---> [*] : (bStart)
	}
	state eInnerState_HomeStepper1 #lightblue {
state "ERROR" as eInnerState_HomeStepper1_ERROR <<exitPoint>> #ff3333
	state eInnerState_HomeStepper1_Node_0 <<choice>>
	[*] ---> eInnerState_HomeStepper1_Node_0 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_HomeStepper1_Node_1 
		state eInnerState_HomeStepper1_Node_2 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_HomeStepper1_Node_3 
	eInnerState_HomeStepper1_Node_2 ---> [*] : (NOT (fbStepper.bError))
	}
	state eInnerState_HomeStepper2 #lightblue {
state "ERROR" as eInnerState_HomeStepper2_ERROR <<exitPoint>> #ff3333
	state eInnerState_HomeStepper2_Node_0 <<choice>>
	[*] ---> eInnerState_HomeStepper2_Node_0 : START
		state eInnerState_HomeStepper2_Node_1 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_HomeStepper2_Node_2 
			state eInnerState_HomeStepper2_Node_3 <<choice>>
	eInnerState_HomeStepper2_Node_3 ---> [*] : (fbStepper.Homed)
			state "fbEventHandler(TASK_FAILED)" as eInnerState_HomeStepper2_Node_4 
	}
	state eInnerState_HomeLinearActuator1 #lightblue {
state "ERROR" as eInnerState_HomeLinearActuator1_ERROR <<exitPoint>> #ff3333
	state eInnerState_HomeLinearActuator1_Node_0 <<choice>>
	[*] ---> eInnerState_HomeLinearActuator1_Node_0 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_HomeLinearActuator1_Node_1 
		state eInnerState_HomeLinearActuator1_Node_2 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_HomeLinearActuator1_Node_3 
	eInnerState_HomeLinearActuator1_Node_2 ---> [*] : (NOT (fbLinearActuator.bError))
	}
	state eInnerState_HomeLinearActuator2 #lightblue {
state "ERROR" as eInnerState_HomeLinearActuator2_ERROR <<exitPoint>> #ff3333
	state eInnerState_HomeLinearActuator2_Node_0 <<choice>>
	[*] ---> eInnerState_HomeLinearActuator2_Node_0 : START
		state eInnerState_HomeLinearActuator2_Node_1 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_HomeLinearActuator2_Node_2 
			state eInnerState_HomeLinearActuator2_Node_3 <<choice>>
	eInnerState_HomeLinearActuator2_Node_3 ---> [*] : (fbLinearActuator.Homed)
			state "fbEventHandler(TASK_FAILED)" as eInnerState_HomeLinearActuator2_Node_4 
	}
	state eInnerState_CalibrateJoints1 #lightblue {
state "ERROR" as eInnerState_CalibrateJoints1_ERROR <<exitPoint>> #ff3333
	state eInnerState_CalibrateJoints1_Node_0 <<choice>>
	[*] ---> eInnerState_CalibrateJoints1_Node_0 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_CalibrateJoints1_Node_1 
		state eInnerState_CalibrateJoints1_Node_2 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_CalibrateJoints1_Node_3 
	eInnerState_CalibrateJoints1_Node_2 ---> [*] : (NOT (fbAllJoints.bError))
	}
	state eInnerState_CalibrateJoints2 #lightblue {
state "ERROR" as eInnerState_CalibrateJoints2_ERROR <<exitPoint>> #ff3333
	state eInnerState_CalibrateJoints2_Node_0 <<choice>>
	[*] ---> eInnerState_CalibrateJoints2_Node_0 : START
		state eInnerState_CalibrateJoints2_Node_1 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_CalibrateJoints2_Node_2 
			state eInnerState_CalibrateJoints2_Node_3 <<choice>>
	eInnerState_CalibrateJoints2_Node_3 ---> [*] : (fbAllJoints.Calibrated)
			state "fbEventHandler(TASK_FAILED)" as eInnerState_CalibrateJoints2_Node_4 
	}
	state eInnerState_CheckEncoderCalibration1 #lightblue {
state "ERROR" as eInnerState_CheckEncoderCalibration1_ERROR <<exitPoint>> #ff3333
	[*] ---> [*]
	}
	state eInnerState_CheckEncoderCalibration2 #lightblue {
state "ERROR" as eInnerState_CheckEncoderCalibration2_ERROR <<exitPoint>> #ff3333
	[*] ---> [*]
	}
	state eInnerState_WrapUp #lightblue {
state "ERROR" as eInnerState_WrapUp_ERROR <<exitPoint>> #ff3333
	[*] ---> [*]
	}
	}
	eInnerState_Idle ---> eInnerState_HomeStepper1 : (bStart)
	eInnerState_HomeStepper1_Node_0 ---> eInnerState_HomeStepper1_Node_1 : (fbStepper.Busy)
	eInnerState_HomeStepper1_Node_1 ---> eInnerState_HomeStepper1_ERROR : (fbStepper.Busy)
	eInnerState_HomeStepper1_Node_0 ---> eInnerState_HomeStepper1_Node_2 : (NOT (fbStepper.Busy))
	eInnerState_HomeStepper1_Node_2 ---> eInnerState_HomeStepper1_Node_3 : (fbStepper.bError)
	eInnerState_HomeStepper1_Node_3 ---> eInnerState_HomeStepper1_ERROR : (fbStepper.bError)
	eInnerState_HomeStepper1 ---> eInnerState_HomeStepper2 : (NOT (fbStepper.bError))
	eInnerState_HomeStepper2_Node_0 ---> eInnerState_HomeStepper2_Node_1 : (NOT (fbStepper.Busy))
	eInnerState_HomeStepper2_Node_1 ---> eInnerState_HomeStepper2_Node_2 : (fbStepper.bError)
	eInnerState_HomeStepper2_Node_2 ---> eInnerState_HomeStepper2_ERROR : (fbStepper.bError)
	eInnerState_HomeStepper2_Node_1 ---> eInnerState_HomeStepper2_Node_3 : (NOT (fbStepper.bError))
	eInnerState_HomeStepper2 ---> eInnerState_HomeLinearActuator1 : (fbStepper.Homed)
	eInnerState_HomeStepper2_Node_3 ---> eInnerState_HomeStepper2_Node_4 : (NOT (fbStepper.Homed))
	eInnerState_HomeStepper2_Node_4 ---> eInnerState_HomeStepper2_ERROR : (NOT (fbStepper.Homed))
	eInnerState_HomeLinearActuator1_Node_0 ---> eInnerState_HomeLinearActuator1_Node_1 : (fbLinearActuator.Busy)
	eInnerState_HomeLinearActuator1_Node_1 ---> eInnerState_HomeLinearActuator1_ERROR : (fbLinearActuator.Busy)
	eInnerState_HomeLinearActuator1_Node_0 ---> eInnerState_HomeLinearActuator1_Node_2 : (NOT (fbLinearActuator.Busy))
	eInnerState_HomeLinearActuator1_Node_2 ---> eInnerState_HomeLinearActuator1_Node_3 : (fbLinearActuator.bError)
	eInnerState_HomeLinearActuator1_Node_3 ---> eInnerState_HomeLinearActuator1_ERROR : (fbLinearActuator.bError)
	eInnerState_HomeLinearActuator1 ---> eInnerState_HomeLinearActuator2 : (NOT (fbLinearActuator.bError))
	eInnerState_HomeLinearActuator2_Node_0 ---> eInnerState_HomeLinearActuator2_Node_1 : (NOT (fbLinearActuator.Busy))
	eInnerState_HomeLinearActuator2_Node_1 ---> eInnerState_HomeLinearActuator2_Node_2 : (fbLinearActuator.bError)
	eInnerState_HomeLinearActuator2_Node_2 ---> eInnerState_HomeLinearActuator2_ERROR : (fbLinearActuator.bError)
	eInnerState_HomeLinearActuator2_Node_1 ---> eInnerState_HomeLinearActuator2_Node_3 : (NOT (fbLinearActuator.bError))
	eInnerState_HomeLinearActuator2 ---> eInnerState_CalibrateJoints1 : (fbLinearActuator.Homed)
	eInnerState_HomeLinearActuator2_Node_3 ---> eInnerState_HomeLinearActuator2_Node_4 : (NOT (fbLinearActuator.Homed))
	eInnerState_HomeLinearActuator2_Node_4 ---> eInnerState_HomeLinearActuator2_ERROR : (NOT (fbLinearActuator.Homed))
	eInnerState_CalibrateJoints1_Node_0 ---> eInnerState_CalibrateJoints1_Node_1 : (fbAllJoints.Busy)
	eInnerState_CalibrateJoints1_Node_1 ---> eInnerState_CalibrateJoints1_ERROR : (fbAllJoints.Busy)
	eInnerState_CalibrateJoints1_Node_0 ---> eInnerState_CalibrateJoints1_Node_2 : (NOT (fbAllJoints.Busy))
	eInnerState_CalibrateJoints1_Node_2 ---> eInnerState_CalibrateJoints1_Node_3 : (fbAllJoints.bError)
	eInnerState_CalibrateJoints1_Node_3 ---> eInnerState_CalibrateJoints1_ERROR : (fbAllJoints.bError)
	eInnerState_CalibrateJoints1 ---> eInnerState_CalibrateJoints2 : (NOT (fbAllJoints.bError))
	eInnerState_CalibrateJoints2_Node_0 ---> eInnerState_CalibrateJoints2_Node_1 : (NOT (fbAllJoints.Busy))
	eInnerState_CalibrateJoints2_Node_1 ---> eInnerState_CalibrateJoints2_Node_2 : (fbAllJoints.bError)
	eInnerState_CalibrateJoints2_Node_2 ---> eInnerState_CalibrateJoints2_ERROR : (fbAllJoints.bError)
	eInnerState_CalibrateJoints2_Node_1 ---> eInnerState_CalibrateJoints2_Node_3 : (NOT (fbAllJoints.bError))
	eInnerState_CalibrateJoints2 ---> eInnerState_CheckEncoderCalibration1 : (fbAllJoints.Calibrated)
	eInnerState_CalibrateJoints2_Node_3 ---> eInnerState_CalibrateJoints2_Node_4 : (NOT (fbAllJoints.Calibrated))
	eInnerState_CalibrateJoints2_Node_4 ---> eInnerState_CalibrateJoints2_ERROR : (NOT (fbAllJoints.Calibrated))
	eInnerState_CheckEncoderCalibration1 ---> eInnerState_CheckEncoderCalibration2
	eInnerState_CheckEncoderCalibration2 ---> eInnerState_WrapUp
	eInnerState_WrapUp ---> eInnerState_Idle
eInnerState : 
eInnerState : 


}

@enduml
