@startuml State Diagram

skin rose
'left to right direction
hide empty description
!theme reddress-lightgreen
title FB_StateMachine State Diagram



state FB_StateMachine{

state eOuterLoopState #03adfc {
	[*] --> eOuterLoopState_Setup : START
	state eOuterLoopState_Setup{
	state "Setup()" as eOuterLoopState_Setup_Node_0
	[*] --> eOuterLoopState_Setup_Node_0 : START
		state eOuterLoopState_Setup_Node_1 <<choice>>
		state "Reset()" as eOuterLoopState_Setup_Node_2
	eOuterLoopState_Setup_Node_2 --> [*] : (bActive)
	eOuterLoopState_Setup_Node_1 --> [*] : (NOT (bActive))
	}
	state eOuterLoopState_Operational{
	state eOuterLoopState_Operational_Node_0 <<choice>>
	[*] --> eOuterLoopState_Operational_Node_0 : START
	eOuterLoopState_Operational_Node_0 --> [*] : (bError)
	state eOuterLoopState_Operational_Node_1 <<choice>>
	state "InnerLoopSM()" as eOuterLoopState_Operational_Node_2
	eOuterLoopState_Operational_Node_1 --> [*] : (NOT (bActive))
	}
	state eOuterLoopState_DisablingInactive{
	state eOuterLoopState_DisablingInactive_Node_0 <<choice>>
	[*] --> eOuterLoopState_DisablingInactive_Node_0 : START
	eOuterLoopState_DisablingInactive_Node_0 --> [*] : (Disable())
	}
	state eOuterLoopState_Inactive{
	state eOuterLoopState_Inactive_Node_0 <<choice>>
	[*] --> eOuterLoopState_Inactive_Node_0 : START
	state "Reset()" as eOuterLoopState_Inactive_Node_1
	eOuterLoopState_Inactive_Node_1 --> [*] : (bActive)
	}
	state eOuterLoopState_DisablingError{
	state eOuterLoopState_DisablingError_Node_0 <<choice>>
	[*] --> eOuterLoopState_DisablingError_Node_0 : START
	eOuterLoopState_DisablingError_Node_0 --> [*] : (Disable())
	}
	state eOuterLoopState_DisabledError{
	state eOuterLoopState_DisabledError_Node_0 <<choice>>
	[*] --> eOuterLoopState_DisabledError_Node_0 : START
	eOuterLoopState_DisabledError_Node_0 --> [*] : (bErrorAck)
	}
	}
	eOuterLoopState_Setup_Node_0 --> eOuterLoopState_Setup_Node_1
	eOuterLoopState_Setup_Node_1 --> eOuterLoopState_Setup_Node_2 : (bActive)
	eOuterLoopState_Setup --> eOuterLoopState_Operational : (bActive)
	eOuterLoopState_Setup --> eOuterLoopState_Inactive : (NOT (bActive))
	eOuterLoopState_Operational --> eOuterLoopState_DisablingError : (bError)
	eOuterLoopState_Operational_Node_0 --> eOuterLoopState_Operational_Node_1 : (NOT (bError))
	eOuterLoopState_Operational_Node_1 --> eOuterLoopState_Operational_Node_2 : (bActive)
	eOuterLoopState_Operational --> eOuterLoopState_DisablingInactive : (NOT (bActive))
	eOuterLoopState_DisablingInactive --> eOuterLoopState_Inactive : (Disable())
	eOuterLoopState_Inactive_Node_0 --> eOuterLoopState_Inactive_Node_1 : (bActive)
	eOuterLoopState_Inactive --> eOuterLoopState_Operational : (bActive)
	eOuterLoopState_DisablingError --> eOuterLoopState_DisabledError : (Disable())
	eOuterLoopState_DisabledError --> eOuterLoopState_Inactive : (bErrorAck)


}

@enduml
