@startuml State Diagram

!theme plain
'skin rose
left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_Ergonomics State Diagram



state FB_Ergonomics{

state eInnerState #84b1f5 {
	[*] --> eInnerState_Idle : START
	state eInnerState_Idle #lightblue {
state "ERROR" as eInnerState_Idle_ERROR <<exitPoint>> #ff3333
	state eInnerState_Idle_Node_1 <<choice>>
	[*] ---> eInnerState_Idle_Node_1 : START
	state "bStart := FALSE;" as eInnerState_Idle_Node_3 
	state "ResetErgonomicsCommands()" as eInnerState_Idle_Node_4 
		state eInnerState_Idle_Node_5 <<choice>>
		state "ChangeState" as eInnerState_Idle_Node_7 
	eInnerState_Idle_Node_5 ---> eInnerState_Idle_Node_7 : (fbStepper.Homed\nAND fbLinearActuator.Homed)
	eInnerState_Idle_Node_7 ---> [*] : eInnerState_Idle->eInnerState_EnableAxes1
		state "fbEventHandler(ERGO_MOTOR_UNHOMED)" as eInnerState_Idle_Node_8 
	}
	state eInnerState_EnableAxes1 #lightblue {
state "ERROR" as eInnerState_EnableAxes1_ERROR <<exitPoint>> #ff3333
	state eInnerState_EnableAxes1_Node_1 <<choice>>
	[*] ---> eInnerState_EnableAxes1_Node_1 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_EnableAxes1_Node_3 
	state "fbLinearActuator.bEnableAxis := TRUE;" as eInnerState_EnableAxes1_Node_4 
	state "fbStepper.bEnableAxis := TRUE;" as eInnerState_EnableAxes1_Node_5 
	state "ChangeState" as eInnerState_EnableAxes1_Node_6 
	eInnerState_EnableAxes1_Node_5 ---> eInnerState_EnableAxes1_Node_6
	eInnerState_EnableAxes1_Node_6 ---> [*] : eInnerState_EnableAxes1->eInnerState_EnableAxes2
	}
	state eInnerState_EnableAxes2 #lightblue {
state "ERROR" as eInnerState_EnableAxes2_ERROR <<exitPoint>> #ff3333
	state eInnerState_EnableAxes2_Node_1 <<choice>>
	[*] ---> eInnerState_EnableAxes2_Node_1 : START
	state "bMotorsDisabled := TRUE;" as eInnerState_EnableAxes2_Node_3 
	state eInnerState_EnableAxes2_Node_4 <<choice>>
	state eInnerState_EnableAxes2_Node_2 <<join>>
	state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_EnableAxes2_Node_5 
	state "fbLinearActuator.ErrorAck := TRUE;" as eInnerState_EnableAxes2_Node_6 
	state "bMotorsDisabled := FALSE;" as eInnerState_EnableAxes2_Node_7 
	state eInnerState_EnableAxes2_Node_2 <<join>>
		state eInnerState_EnableAxes2_Node_8 <<choice>>
		state "bMotorsDisabled := TRUE;" as eInnerState_EnableAxes2_Node_10 
		state eInnerState_EnableAxes2_Node_11 <<choice>>
	state eInnerState_EnableAxes2_Node_9 <<join>>
		state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_EnableAxes2_Node_12 
		state "fbStepper.ErrorAck := TRUE;" as eInnerState_EnableAxes2_Node_13 
		state "bMotorsDisabled := FALSE;" as eInnerState_EnableAxes2_Node_14 
	state eInnerState_EnableAxes2_Node_9 <<join>>
		state eInnerState_EnableAxes2_Node_15 <<choice>>
		state "ChangeState" as eInnerState_EnableAxes2_Node_17 
	eInnerState_EnableAxes2_Node_15 ---> eInnerState_EnableAxes2_Node_17 : (NOT bMotorsDisabled)
	eInnerState_EnableAxes2_Node_17 ---> [*] : eInnerState_EnableAxes2->eInnerState_WaitForCommand
	}
	state eInnerState_WaitForCommand #lightblue {
state "ERROR" as eInnerState_WaitForCommand_ERROR <<exitPoint>> #ff3333
	state eInnerState_WaitForCommand_Node_1 <<choice>>
	[*] ---> eInnerState_WaitForCommand_Node_1 : START
	state "fbEventHandler(DEBUG_TEST2)" as eInnerState_WaitForCommand_Node_3 
	state "bStop := FALSE;" as eInnerState_WaitForCommand_Node_4 
	state "stErgoCommands.Done := FALSE;" as eInnerState_WaitForCommand_Node_5 
	state "ChangeState" as eInnerState_WaitForCommand_Node_6 
	eInnerState_WaitForCommand_Node_5 ---> eInnerState_WaitForCommand_Node_6
	eInnerState_WaitForCommand_Node_6 ---> [*] : eInnerState_WaitForCommand->eInnerState_DisableMotors1
		state eInnerState_WaitForCommand_Node_7 <<choice>>
		state "stErgoCommands.bApplyUserConfig_FE := FALSE;" as eInnerState_WaitForCommand_Node_9 
		state "fbStepper.fSetAngle := stErgoCommands.fStepperAngle_FE;" as eInnerState_WaitForCommand_Node_10 
		state "ChangeState" as eInnerState_WaitForCommand_Node_11 
	eInnerState_WaitForCommand_Node_10 ---> eInnerState_WaitForCommand_Node_11
	eInnerState_WaitForCommand_Node_11 ---> [*] : eInnerState_WaitForCommand->eInnerState_SetStepperAngle1
		state eInnerState_WaitForCommand_Node_12 <<choice>>
		state "fbStepper.eJogDirection := stErgoCommands.eStepperJoggingDir_FE;" as eInnerState_WaitForCommand_Node_13 
		state "stErgoCommands.eStepperJoggingDir_FE := E_StepperMotorMovingDirection.None;" as eInnerState_WaitForCommand_Node_14 
		state "ChangeState" as eInnerState_WaitForCommand_Node_15 
	eInnerState_WaitForCommand_Node_14 ---> eInnerState_WaitForCommand_Node_15
	eInnerState_WaitForCommand_Node_15 ---> [*] : eInnerState_WaitForCommand->eInnerState_JogStepper1
		state eInnerState_WaitForCommand_Node_16 <<choice>>
		state "fbLinearActuator.eJogDirection := stErgoCommands.eLAJoggingDir_FE;" as eInnerState_WaitForCommand_Node_17 
		state "stErgoCommands.eStepperJoggingDir_FE := E_LinearActuatorMovingDirection.None;" as eInnerState_WaitForCommand_Node_18 
		state "ChangeState" as eInnerState_WaitForCommand_Node_19 
	eInnerState_WaitForCommand_Node_18 ---> eInnerState_WaitForCommand_Node_19
	eInnerState_WaitForCommand_Node_19 ---> [*] : eInnerState_WaitForCommand->eInnerState_JogLinActuator1
	}
	state eInnerState_SetStepperAngle1 #lightblue {
state "ERROR" as eInnerState_SetStepperAngle1_ERROR <<exitPoint>> #ff3333
	state eInnerState_SetStepperAngle1_Node_1 <<choice>>
	[*] ---> eInnerState_SetStepperAngle1_Node_1 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_SetStepperAngle1_Node_3 
		state eInnerState_SetStepperAngle1_Node_4 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_SetStepperAngle1_Node_6 
		state "fbStepper.ErrorAck := TRUE;" as eInnerState_SetStepperAngle1_Node_7 
		state "fbStepper.bStartErgoAng:=TRUE;" as eInnerState_SetStepperAngle1_Node_8 
		state "ChangeState" as eInnerState_SetStepperAngle1_Node_9 
	eInnerState_SetStepperAngle1_Node_8 ---> eInnerState_SetStepperAngle1_Node_9
	eInnerState_SetStepperAngle1_Node_9 ---> [*] : eInnerState_SetStepperAngle1->eInnerState_SetStepperAngle2
	}
	state eInnerState_SetStepperAngle2 #lightblue {
state "ERROR" as eInnerState_SetStepperAngle2_ERROR <<exitPoint>> #ff3333
	state eInnerState_SetStepperAngle2_Node_1 <<choice>>
	[*] ---> eInnerState_SetStepperAngle2_Node_1 : START
	state "bStop := FALSE;" as eInnerState_SetStepperAngle2_Node_3 
	state "fbStepper.bStopAxis := TRUE;" as eInnerState_SetStepperAngle2_Node_4 
	state "ChangeState" as eInnerState_SetStepperAngle2_Node_5 
	eInnerState_SetStepperAngle2_Node_4 ---> eInnerState_SetStepperAngle2_Node_5
	eInnerState_SetStepperAngle2_Node_5 ---> [*] : eInnerState_SetStepperAngle2->eInnerState_StopStepper
		state eInnerState_SetStepperAngle2_Node_6 <<choice>>
			state eInnerState_SetStepperAngle2_Node_8 <<choice>>
			state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_SetStepperAngle2_Node_9 
			state "fbStepper.ErrorAck := TRUE;" as eInnerState_SetStepperAngle2_Node_10 
			state "ChangeState" as eInnerState_SetStepperAngle2_Node_11 
	eInnerState_SetStepperAngle2_Node_8 ---> eInnerState_SetStepperAngle2_Node_11 : (NOT (fbStepper.bError))
	eInnerState_SetStepperAngle2_Node_11 ---> [*] : eInnerState_SetStepperAngle2->eInnerState_WaitForCommand
	}
	state eInnerState_JogStepper1 #lightblue {
state "ERROR" as eInnerState_JogStepper1_ERROR <<exitPoint>> #ff3333
	state eInnerState_JogStepper1_Node_1 <<choice>>
	[*] ---> eInnerState_JogStepper1_Node_1 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_JogStepper1_Node_3 
		state eInnerState_JogStepper1_Node_4 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_JogStepper1_Node_6 
		state "fbStepper.ErrorAck := TRUE;" as eInnerState_JogStepper1_Node_7 
		state "fbStepper.bStartErgoJog:=TRUE;" as eInnerState_JogStepper1_Node_8 
		state "ChangeState" as eInnerState_JogStepper1_Node_9 
	eInnerState_JogStepper1_Node_8 ---> eInnerState_JogStepper1_Node_9
	eInnerState_JogStepper1_Node_9 ---> [*] : eInnerState_JogStepper1->eInnerState_JogStepper2
	}
	state eInnerState_JogStepper2 #lightblue {
state "ERROR" as eInnerState_JogStepper2_ERROR <<exitPoint>> #ff3333
	state eInnerState_JogStepper2_Node_1 <<choice>>
	[*] ---> eInnerState_JogStepper2_Node_1 : START
	state "bStop := FALSE;" as eInnerState_JogStepper2_Node_3 
	state "fbStepper.bStopAxis := TRUE;" as eInnerState_JogStepper2_Node_4 
	state "ChangeState" as eInnerState_JogStepper2_Node_5 
	eInnerState_JogStepper2_Node_4 ---> eInnerState_JogStepper2_Node_5
	eInnerState_JogStepper2_Node_5 ---> [*] : eInnerState_JogStepper2->eInnerState_StopStepper
		state eInnerState_JogStepper2_Node_6 <<choice>>
			state eInnerState_JogStepper2_Node_8 <<choice>>
			state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_JogStepper2_Node_9 
			state "fbStepper.ErrorAck := TRUE;" as eInnerState_JogStepper2_Node_10 
			state "ChangeState" as eInnerState_JogStepper2_Node_11 
	eInnerState_JogStepper2_Node_8 ---> eInnerState_JogStepper2_Node_11 : (NOT (fbStepper.bError))
	eInnerState_JogStepper2_Node_11 ---> [*] : eInnerState_JogStepper2->eInnerState_WaitForCommand
	}
	state eInnerState_JogLinActuator1 #lightblue {
state "ERROR" as eInnerState_JogLinActuator1_ERROR <<exitPoint>> #ff3333
	state eInnerState_JogLinActuator1_Node_1 <<choice>>
	[*] ---> eInnerState_JogLinActuator1_Node_1 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_JogLinActuator1_Node_3 
		state eInnerState_JogLinActuator1_Node_4 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_JogLinActuator1_Node_6 
		state "fbLinearActuator.ErrorAck := TRUE;" as eInnerState_JogLinActuator1_Node_7 
		state "fbLinearActuator.bStartErgoJog := TRUE;" as eInnerState_JogLinActuator1_Node_8 
		state "ChangeState" as eInnerState_JogLinActuator1_Node_9 
	eInnerState_JogLinActuator1_Node_8 ---> eInnerState_JogLinActuator1_Node_9
	eInnerState_JogLinActuator1_Node_9 ---> [*] : eInnerState_JogLinActuator1->eInnerState_JogLinActuator2
	}
	state eInnerState_JogLinActuator2 #lightblue {
state "ERROR" as eInnerState_JogLinActuator2_ERROR <<exitPoint>> #ff3333
	state eInnerState_JogLinActuator2_Node_1 <<choice>>
	[*] ---> eInnerState_JogLinActuator2_Node_1 : START
	state "bStop := FALSE;" as eInnerState_JogLinActuator2_Node_3 
	state "fbLinearActuator.bStopAxis := TRUE;" as eInnerState_JogLinActuator2_Node_4 
	state "ChangeState" as eInnerState_JogLinActuator2_Node_5 
	eInnerState_JogLinActuator2_Node_4 ---> eInnerState_JogLinActuator2_Node_5
	eInnerState_JogLinActuator2_Node_5 ---> [*] : eInnerState_JogLinActuator2->eInnerState_StopLinearActuator
		state eInnerState_JogLinActuator2_Node_6 <<choice>>
			state eInnerState_JogLinActuator2_Node_8 <<choice>>
			state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_JogLinActuator2_Node_9 
			state "fbLinearActuator.ErrorAck := TRUE;" as eInnerState_JogLinActuator2_Node_10 
			state "ChangeState" as eInnerState_JogLinActuator2_Node_11 
	eInnerState_JogLinActuator2_Node_8 ---> eInnerState_JogLinActuator2_Node_11 : (NOT (fbLinearActuator.bError))
	eInnerState_JogLinActuator2_Node_11 ---> [*] : eInnerState_JogLinActuator2->eInnerState_WaitForCommand
	}
	state eInnerState_DisableMotors1 #lightblue {
state "ERROR" as eInnerState_DisableMotors1_ERROR <<exitPoint>> #ff3333
	state eInnerState_DisableMotors1_Node_1 <<choice>>
	[*] ---> eInnerState_DisableMotors1_Node_1 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_DisableMotors1_Node_3 
	state "fbLinearActuator.bDisableAxis := TRUE;" as eInnerState_DisableMotors1_Node_4 
	state "fbStepper.bDisableAxis := TRUE;" as eInnerState_DisableMotors1_Node_5 
	state "ChangeState" as eInnerState_DisableMotors1_Node_6 
	eInnerState_DisableMotors1_Node_5 ---> eInnerState_DisableMotors1_Node_6
	eInnerState_DisableMotors1_Node_6 ---> [*] : eInnerState_DisableMotors1->eInnerState_DisableMotors2
	}
	state eInnerState_DisableMotors2 #lightblue {
state "ERROR" as eInnerState_DisableMotors2_ERROR <<exitPoint>> #ff3333
	state eInnerState_DisableMotors2_Node_1 <<choice>>
	[*] ---> eInnerState_DisableMotors2_Node_1 : START
	state "bMotorsDisabled := FALSE;" as eInnerState_DisableMotors2_Node_3 
	state eInnerState_DisableMotors2_Node_4 <<choice>>
	state eInnerState_DisableMotors2_Node_2 <<join>>
	state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_DisableMotors2_Node_5 
	state "fbLinearActuator.ErrorAck := TRUE;" as eInnerState_DisableMotors2_Node_6 
		state eInnerState_DisableMotors2_Node_7 <<choice>>
		state "bMotorsDisabled := FALSE;" as eInnerState_DisableMotors2_Node_9 
		state eInnerState_DisableMotors2_Node_10 <<choice>>
	state eInnerState_DisableMotors2_Node_8 <<join>>
		state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_DisableMotors2_Node_11 
		state "fbStepper.ErrorAck := TRUE;" as eInnerState_DisableMotors2_Node_12 
		state eInnerState_DisableMotors2_Node_13 <<choice>>
		state "ChangeState" as eInnerState_DisableMotors2_Node_15 
	eInnerState_DisableMotors2_Node_13 ---> eInnerState_DisableMotors2_Node_15 : (bMotorsDisabled)
	eInnerState_DisableMotors2_Node_15 ---> [*] : eInnerState_DisableMotors2->eInnerState_Idle
	}
	state eInnerState_StopStepper #lightblue {
state "ERROR" as eInnerState_StopStepper_ERROR <<exitPoint>> #ff3333
	state eInnerState_StopStepper_Node_1 <<choice>>
	[*] ---> eInnerState_StopStepper_Node_1 : START
		state eInnerState_StopStepper_Node_3 <<choice>>
		state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_StopStepper_Node_5 
		state "fbStepper.ErrorAck := TRUE;" as eInnerState_StopStepper_Node_6 
		state "ChangeState" as eInnerState_StopStepper_Node_7 
	eInnerState_StopStepper_Node_3 ---> eInnerState_StopStepper_Node_7 : (NOT (fbStepper.bError))
	eInnerState_StopStepper_Node_7 ---> [*] : eInnerState_StopStepper->eInnerState_DisableMotors1
	}
	state eInnerState_StopLinearActuator #lightblue {
state "ERROR" as eInnerState_StopLinearActuator_ERROR <<exitPoint>> #ff3333
	state eInnerState_StopLinearActuator_Node_1 <<choice>>
	[*] ---> eInnerState_StopLinearActuator_Node_1 : START
		state eInnerState_StopLinearActuator_Node_3 <<choice>>
		state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_StopLinearActuator_Node_5 
		state "fbLinearActuator.ErrorAck := TRUE;" as eInnerState_StopLinearActuator_Node_6 
		state "ChangeState" as eInnerState_StopLinearActuator_Node_7 
	eInnerState_StopLinearActuator_Node_3 ---> eInnerState_StopLinearActuator_Node_7 : (NOT (fbLinearActuator.bError))
	eInnerState_StopLinearActuator_Node_7 ---> [*] : eInnerState_StopLinearActuator->eInnerState_DisableMotors1
	}
	}
	eInnerState_Idle_Node_1 ---> eInnerState_Idle_Node_3 : (bStart)
	eInnerState_Idle_Node_3 ---> eInnerState_Idle_Node_4
	eInnerState_Idle_Node_4 ---> eInnerState_Idle_Node_5
	eInnerState_Idle ---> eInnerState_EnableAxes1 : eInnerState_Idle->eInnerState_EnableAxes1
	eInnerState_Idle_Node_5 ---> eInnerState_Idle_Node_8 : (NOT (fbStepper.Homed\nAND fbLinearActuator.Homed))
	eInnerState_Idle_Node_8 ---> eInnerState_Idle_ERROR : (NOT (fbStepper.Homed\nAND fbLinearActuator.Homed))
	eInnerState_EnableAxes1_Node_1 ---> eInnerState_EnableAxes1_Node_3 : (NOT (fbStepper.Ready\nAND fbLinearActuator.Ready))
	eInnerState_EnableAxes1_Node_3 ---> eInnerState_EnableAxes1_ERROR : (NOT (fbStepper.Ready\nAND fbLinearActuator.Ready))
	eInnerState_EnableAxes1_Node_1 ---> eInnerState_EnableAxes1_Node_4 : ((fbStepper.Ready\nAND fbLinearActuator.Ready))
	eInnerState_EnableAxes1_Node_4 ---> eInnerState_EnableAxes1_Node_5
	eInnerState_EnableAxes1 ---> eInnerState_EnableAxes2 : eInnerState_EnableAxes1->eInnerState_EnableAxes2
	eInnerState_EnableAxes2_Node_1 ---> eInnerState_EnableAxes2_Node_3 : (fbLinearActuator.Busy)
	eInnerState_EnableAxes2_Node_3 ---> eInnerState_EnableAxes2_Node_2
	eInnerState_EnableAxes2_Node_1 ---> eInnerState_EnableAxes2_Node_4 : (NOT (fbLinearActuator.Busy))
	eInnerState_EnableAxes2_Node_4 ---> eInnerState_EnableAxes2_Node_5 : (fbLinearActuator.bError)
	eInnerState_EnableAxes2_Node_5 ---> eInnerState_EnableAxes2_Node_6
	eInnerState_EnableAxes2_Node_6 ---> eInnerState_EnableAxes2_ERROR : (fbLinearActuator.bError)
	eInnerState_EnableAxes2_Node_4 ---> eInnerState_EnableAxes2_Node_7 : (NOT (fbLinearActuator.bError))
	eInnerState_EnableAxes2_Node_7 ---> eInnerState_EnableAxes2_Node_2
	eInnerState_EnableAxes2_Node_2 ---> eInnerState_EnableAxes2_Node_8
	eInnerState_EnableAxes2_Node_8 ---> eInnerState_EnableAxes2_Node_10 : (fbStepper.Busy)
	eInnerState_EnableAxes2_Node_10 ---> eInnerState_EnableAxes2_Node_9
	eInnerState_EnableAxes2_Node_8 ---> eInnerState_EnableAxes2_Node_11 : (NOT (fbStepper.Busy))
	eInnerState_EnableAxes2_Node_11 ---> eInnerState_EnableAxes2_Node_12 : (fbStepper.bError)
	eInnerState_EnableAxes2_Node_12 ---> eInnerState_EnableAxes2_Node_13
	eInnerState_EnableAxes2_Node_13 ---> eInnerState_EnableAxes2_ERROR : (fbStepper.bError)
	eInnerState_EnableAxes2_Node_11 ---> eInnerState_EnableAxes2_Node_14 : (NOT (fbStepper.bError))
	eInnerState_EnableAxes2_Node_14 ---> eInnerState_EnableAxes2_Node_9
	eInnerState_EnableAxes2_Node_9 ---> eInnerState_EnableAxes2_Node_15
	eInnerState_EnableAxes2 ---> eInnerState_WaitForCommand : eInnerState_EnableAxes2->eInnerState_WaitForCommand
	eInnerState_WaitForCommand_Node_1 ---> eInnerState_WaitForCommand_Node_3 : (stErgoCommands.Done\nOR bStop)
	eInnerState_WaitForCommand_Node_3 ---> eInnerState_WaitForCommand_Node_4
	eInnerState_WaitForCommand_Node_4 ---> eInnerState_WaitForCommand_Node_5
	eInnerState_WaitForCommand ---> eInnerState_DisableMotors1 : eInnerState_WaitForCommand->eInnerState_DisableMotors1
	eInnerState_WaitForCommand_Node_1 ---> eInnerState_WaitForCommand_Node_7 : (NOT (stErgoCommands.Done\nOR bStop))
	eInnerState_WaitForCommand_Node_7 ---> eInnerState_WaitForCommand_Node_9 : (stErgoCommands.bApplyUserConfig_FE)
	eInnerState_WaitForCommand_Node_9 ---> eInnerState_WaitForCommand_Node_10
	eInnerState_WaitForCommand ---> eInnerState_SetStepperAngle1 : eInnerState_WaitForCommand->eInnerState_SetStepperAngle1
	eInnerState_WaitForCommand_Node_7 ---> eInnerState_WaitForCommand_Node_12 : (NOT (stErgoCommands.bApplyUserConfig_FE))
	eInnerState_WaitForCommand_Node_12 ---> eInnerState_WaitForCommand_Node_13 : (StepperJogRequired())
	eInnerState_WaitForCommand_Node_13 ---> eInnerState_WaitForCommand_Node_14
	eInnerState_WaitForCommand ---> eInnerState_JogStepper1 : eInnerState_WaitForCommand->eInnerState_JogStepper1
	eInnerState_WaitForCommand_Node_12 ---> eInnerState_WaitForCommand_Node_16 : (NOT (StepperJogRequired()))
	eInnerState_WaitForCommand_Node_16 ---> eInnerState_WaitForCommand_Node_17 : (LinActuatorJogRequired())
	eInnerState_WaitForCommand_Node_17 ---> eInnerState_WaitForCommand_Node_18
	eInnerState_WaitForCommand ---> eInnerState_JogLinActuator1 : eInnerState_WaitForCommand->eInnerState_JogLinActuator1
	eInnerState_SetStepperAngle1_Node_1 ---> eInnerState_SetStepperAngle1_Node_3 : (fbStepper.Busy)
	eInnerState_SetStepperAngle1_Node_3 ---> eInnerState_SetStepperAngle1_ERROR : (fbStepper.Busy)
	eInnerState_SetStepperAngle1_Node_1 ---> eInnerState_SetStepperAngle1_Node_4 : (NOT (fbStepper.Busy))
	eInnerState_SetStepperAngle1_Node_4 ---> eInnerState_SetStepperAngle1_Node_6 : (fbStepper.bError)
	eInnerState_SetStepperAngle1_Node_6 ---> eInnerState_SetStepperAngle1_Node_7
	eInnerState_SetStepperAngle1_Node_7 ---> eInnerState_SetStepperAngle1_ERROR : (fbStepper.bError)
	eInnerState_SetStepperAngle1_Node_4 ---> eInnerState_SetStepperAngle1_Node_8 : (NOT (fbStepper.bError))
	eInnerState_SetStepperAngle1 ---> eInnerState_SetStepperAngle2 : eInnerState_SetStepperAngle1->eInnerState_SetStepperAngle2
	eInnerState_SetStepperAngle2_Node_1 ---> eInnerState_SetStepperAngle2_Node_3 : (bStop)
	eInnerState_SetStepperAngle2_Node_3 ---> eInnerState_SetStepperAngle2_Node_4
	eInnerState_SetStepperAngle2 ---> eInnerState_StopStepper : eInnerState_SetStepperAngle2->eInnerState_StopStepper
	eInnerState_SetStepperAngle2_Node_1 ---> eInnerState_SetStepperAngle2_Node_6 : (NOT (bStop))
	eInnerState_SetStepperAngle2_Node_6 ---> eInnerState_SetStepperAngle2_Node_8 : (NOT (fbStepper.Busy))
	eInnerState_SetStepperAngle2_Node_8 ---> eInnerState_SetStepperAngle2_Node_9 : (fbStepper.bError)
	eInnerState_SetStepperAngle2_Node_9 ---> eInnerState_SetStepperAngle2_Node_10
	eInnerState_SetStepperAngle2_Node_10 ---> eInnerState_SetStepperAngle2_ERROR : (fbStepper.bError)
	eInnerState_SetStepperAngle2 ---> eInnerState_WaitForCommand : eInnerState_SetStepperAngle2->eInnerState_WaitForCommand
	eInnerState_JogStepper1_Node_1 ---> eInnerState_JogStepper1_Node_3 : (fbStepper.Busy)
	eInnerState_JogStepper1_Node_3 ---> eInnerState_JogStepper1_ERROR : (fbStepper.Busy)
	eInnerState_JogStepper1_Node_1 ---> eInnerState_JogStepper1_Node_4 : (NOT (fbStepper.Busy))
	eInnerState_JogStepper1_Node_4 ---> eInnerState_JogStepper1_Node_6 : (fbStepper.bError)
	eInnerState_JogStepper1_Node_6 ---> eInnerState_JogStepper1_Node_7
	eInnerState_JogStepper1_Node_7 ---> eInnerState_JogStepper1_ERROR : (fbStepper.bError)
	eInnerState_JogStepper1_Node_4 ---> eInnerState_JogStepper1_Node_8 : (NOT (fbStepper.bError))
	eInnerState_JogStepper1 ---> eInnerState_JogStepper2 : eInnerState_JogStepper1->eInnerState_JogStepper2
	eInnerState_JogStepper2_Node_1 ---> eInnerState_JogStepper2_Node_3 : (bStop)
	eInnerState_JogStepper2_Node_3 ---> eInnerState_JogStepper2_Node_4
	eInnerState_JogStepper2 ---> eInnerState_StopStepper : eInnerState_JogStepper2->eInnerState_StopStepper
	eInnerState_JogStepper2_Node_1 ---> eInnerState_JogStepper2_Node_6 : (NOT (bStop))
	eInnerState_JogStepper2_Node_6 ---> eInnerState_JogStepper2_Node_8 : (NOT (fbStepper.Busy))
	eInnerState_JogStepper2_Node_8 ---> eInnerState_JogStepper2_Node_9 : (fbStepper.bError)
	eInnerState_JogStepper2_Node_9 ---> eInnerState_JogStepper2_Node_10
	eInnerState_JogStepper2_Node_10 ---> eInnerState_JogStepper2_ERROR : (fbStepper.bError)
	eInnerState_JogStepper2 ---> eInnerState_WaitForCommand : eInnerState_JogStepper2->eInnerState_WaitForCommand
	eInnerState_JogLinActuator1_Node_1 ---> eInnerState_JogLinActuator1_Node_3 : (fbLinearActuator.Busy)
	eInnerState_JogLinActuator1_Node_3 ---> eInnerState_JogLinActuator1_ERROR : (fbLinearActuator.Busy)
	eInnerState_JogLinActuator1_Node_1 ---> eInnerState_JogLinActuator1_Node_4 : (NOT (fbLinearActuator.Busy))
	eInnerState_JogLinActuator1_Node_4 ---> eInnerState_JogLinActuator1_Node_6 : (fbLinearActuator.bError)
	eInnerState_JogLinActuator1_Node_6 ---> eInnerState_JogLinActuator1_Node_7
	eInnerState_JogLinActuator1_Node_7 ---> eInnerState_JogLinActuator1_ERROR : (fbLinearActuator.bError)
	eInnerState_JogLinActuator1_Node_4 ---> eInnerState_JogLinActuator1_Node_8 : (NOT (fbLinearActuator.bError))
	eInnerState_JogLinActuator1 ---> eInnerState_JogLinActuator2 : eInnerState_JogLinActuator1->eInnerState_JogLinActuator2
	eInnerState_JogLinActuator2_Node_1 ---> eInnerState_JogLinActuator2_Node_3 : (bStop)
	eInnerState_JogLinActuator2_Node_3 ---> eInnerState_JogLinActuator2_Node_4
	eInnerState_JogLinActuator2 ---> eInnerState_StopLinearActuator : eInnerState_JogLinActuator2->eInnerState_StopLinearActuator
	eInnerState_JogLinActuator2_Node_1 ---> eInnerState_JogLinActuator2_Node_6 : (NOT (bStop))
	eInnerState_JogLinActuator2_Node_6 ---> eInnerState_JogLinActuator2_Node_8 : (NOT (fbLinearActuator.Busy))
	eInnerState_JogLinActuator2_Node_8 ---> eInnerState_JogLinActuator2_Node_9 : (fbLinearActuator.bError)
	eInnerState_JogLinActuator2_Node_9 ---> eInnerState_JogLinActuator2_Node_10
	eInnerState_JogLinActuator2_Node_10 ---> eInnerState_JogLinActuator2_ERROR : (fbLinearActuator.bError)
	eInnerState_JogLinActuator2 ---> eInnerState_WaitForCommand : eInnerState_JogLinActuator2->eInnerState_WaitForCommand
	eInnerState_DisableMotors1_Node_1 ---> eInnerState_DisableMotors1_Node_3 : (NOT (fbStepper.Ready\nAND fbLinearActuator.Ready))
	eInnerState_DisableMotors1_Node_3 ---> eInnerState_DisableMotors1_ERROR : (NOT (fbStepper.Ready\nAND fbLinearActuator.Ready))
	eInnerState_DisableMotors1_Node_1 ---> eInnerState_DisableMotors1_Node_4 : ((fbStepper.Ready\nAND fbLinearActuator.Ready))
	eInnerState_DisableMotors1_Node_4 ---> eInnerState_DisableMotors1_Node_5
	eInnerState_DisableMotors1 ---> eInnerState_DisableMotors2 : eInnerState_DisableMotors1->eInnerState_DisableMotors2
	eInnerState_DisableMotors2_Node_1 ---> eInnerState_DisableMotors2_Node_3 : (fbLinearActuator.Busy)
	eInnerState_DisableMotors2_Node_3 ---> eInnerState_DisableMotors2_Node_2
	eInnerState_DisableMotors2_Node_1 ---> eInnerState_DisableMotors2_Node_4 : (NOT (fbLinearActuator.Busy))
	eInnerState_DisableMotors2_Node_4 ---> eInnerState_DisableMotors2_Node_5 : (fbLinearActuator.bError)
	eInnerState_DisableMotors2_Node_5 ---> eInnerState_DisableMotors2_Node_6
	eInnerState_DisableMotors2_Node_6 ---> eInnerState_DisableMotors2_ERROR : (fbLinearActuator.bError)
	eInnerState_DisableMotors2_Node_2 ---> eInnerState_DisableMotors2_Node_7
	eInnerState_DisableMotors2_Node_7 ---> eInnerState_DisableMotors2_Node_9 : (fbStepper.Busy)
	eInnerState_DisableMotors2_Node_9 ---> eInnerState_DisableMotors2_Node_8
	eInnerState_DisableMotors2_Node_7 ---> eInnerState_DisableMotors2_Node_10 : (NOT (fbStepper.Busy))
	eInnerState_DisableMotors2_Node_10 ---> eInnerState_DisableMotors2_Node_11 : (fbStepper.bError)
	eInnerState_DisableMotors2_Node_11 ---> eInnerState_DisableMotors2_Node_12
	eInnerState_DisableMotors2_Node_12 ---> eInnerState_DisableMotors2_ERROR : (fbStepper.bError)
	eInnerState_DisableMotors2_Node_8 ---> eInnerState_DisableMotors2_Node_13
	eInnerState_DisableMotors2 ---> eInnerState_Idle : eInnerState_DisableMotors2->eInnerState_Idle
	eInnerState_StopStepper_Node_1 ---> eInnerState_StopStepper_Node_3 : (NOT (fbStepper.Busy))
	eInnerState_StopStepper_Node_3 ---> eInnerState_StopStepper_Node_5 : (fbStepper.bError)
	eInnerState_StopStepper_Node_5 ---> eInnerState_StopStepper_Node_6
	eInnerState_StopStepper_Node_6 ---> eInnerState_StopStepper_ERROR : (fbStepper.bError)
	eInnerState_StopStepper ---> eInnerState_DisableMotors1 : eInnerState_StopStepper->eInnerState_DisableMotors1
	eInnerState_StopLinearActuator_Node_1 ---> eInnerState_StopLinearActuator_Node_3 : (NOT (fbLinearActuator.Busy))
	eInnerState_StopLinearActuator_Node_3 ---> eInnerState_StopLinearActuator_Node_5 : (fbLinearActuator.bError)
	eInnerState_StopLinearActuator_Node_5 ---> eInnerState_StopLinearActuator_Node_6
	eInnerState_StopLinearActuator_Node_6 ---> eInnerState_StopLinearActuator_ERROR : (fbLinearActuator.bError)
	eInnerState_StopLinearActuator ---> eInnerState_DisableMotors1 : eInnerState_StopLinearActuator->eInnerState_DisableMotors1
eInnerState : 
eInnerState : 


}

@enduml
