@startuml State Diagram

!theme plain
'skin rose
left to right direction
hide empty description
'!theme reddress-lightgreen
title FB_Teleoperation State Diagram



state FB_Teleoperation{

state eInnerState #84b1f5 {
	[*] --> eInnerState_Idle : START
	state eInnerState_Idle #lightblue {
state "ERROR" as eInnerState_Idle_ERROR <<exitPoint>> #ff3333
	state eInnerState_Idle_Node_1 <<choice>>
	[*] ---> eInnerState_Idle_Node_1 : START
	state "bStart := FALSE;" as eInnerState_Idle_Node_3 
	state "ChangeState" as eInnerState_Idle_Node_4 
	eInnerState_Idle_Node_3 ---> eInnerState_Idle_Node_4
	eInnerState_Idle_Node_4 ---> [*] : eInnerState_Idle->eInnerState_StartDataProcessing1
	}
	state eInnerState_StartDataProcessing1 #lightblue {
state "ERROR" as eInnerState_StartDataProcessing1_ERROR <<exitPoint>> #ff3333
	state eInnerState_StartDataProcessing1_Node_1 <<choice>>
	[*] ---> eInnerState_StartDataProcessing1_Node_1 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_StartDataProcessing1_Node_3 
		state eInnerState_StartDataProcessing1_Node_4 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_StartDataProcessing1_Node_6 
		state "fbKnS.ErrorAck:=TRUE;" as eInnerState_StartDataProcessing1_Node_7 
		state "fbKnS.bStart := TRUE;" as eInnerState_StartDataProcessing1_Node_8 
		state "ChangeState" as eInnerState_StartDataProcessing1_Node_9 
	eInnerState_StartDataProcessing1_Node_8 ---> eInnerState_StartDataProcessing1_Node_9
	eInnerState_StartDataProcessing1_Node_9 ---> [*] : eInnerState_StartDataProcessing1->eInnerState_StartDataProcessing2
	}
	state eInnerState_StartDataProcessing2 #lightblue {
state "ERROR" as eInnerState_StartDataProcessing2_ERROR <<exitPoint>> #ff3333
	state eInnerState_StartDataProcessing2_Node_1 <<choice>>
	[*] ---> eInnerState_StartDataProcessing2_Node_1 : START
	state "ChangeState" as eInnerState_StartDataProcessing2_Node_3 
	eInnerState_StartDataProcessing2_Node_1 ---> eInnerState_StartDataProcessing2_Node_3 : (fbKnS.Processing)
	eInnerState_StartDataProcessing2_Node_3 ---> [*] : eInnerState_StartDataProcessing2->eInnerState_StartCommRM1
		state eInnerState_StartDataProcessing2_Node_4 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_StartDataProcessing2_Node_6 
		state "fbKnS.ErrorAck:=TRUE;" as eInnerState_StartDataProcessing2_Node_7 
	}
	state eInnerState_StartCommRM1 #lightblue {
state "ERROR" as eInnerState_StartCommRM1_ERROR <<exitPoint>> #ff3333
	state eInnerState_StartCommRM1_Node_1 <<choice>>
	[*] ---> eInnerState_StartCommRM1_Node_1 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_StartCommRM1_Node_3 
		state eInnerState_StartCommRM1_Node_4 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_StartCommRM1_Node_6 
		state "fbRemoteManipulator.ErrorAck:=TRUE;" as eInnerState_StartCommRM1_Node_7 
		state "fbRemoteManipulator.bEstablishComm :=TRUE;" as eInnerState_StartCommRM1_Node_8 
		state "ChangeState" as eInnerState_StartCommRM1_Node_9 
	eInnerState_StartCommRM1_Node_8 ---> eInnerState_StartCommRM1_Node_9
	eInnerState_StartCommRM1_Node_9 ---> [*] : eInnerState_StartCommRM1->eInnerState_StartCommRM2
	}
	state eInnerState_StartCommRM2 #lightblue {
state "ERROR" as eInnerState_StartCommRM2_ERROR <<exitPoint>> #ff3333
	state eInnerState_StartCommRM2_Node_1 <<choice>>
	[*] ---> eInnerState_StartCommRM2_Node_1 : START
	state "fbEventHandler(TASK_FAILED)" as eInnerState_StartCommRM2_Node_3 
	state "fbRemoteManipulator.ErrorAck:=TRUE;" as eInnerState_StartCommRM2_Node_4 
		state eInnerState_StartCommRM2_Node_5 <<choice>>
		state "ChangeState" as eInnerState_StartCommRM2_Node_7 
	eInnerState_StartCommRM2_Node_5 ---> eInnerState_StartCommRM2_Node_7 : (fbRemoteManipulator.Connected)
	eInnerState_StartCommRM2_Node_7 ---> [*] : eInnerState_StartCommRM2->eInnerState_EnableArmMotors1
	}
	state eInnerState_EnableArmMotors1 #lightblue {
state "ERROR" as eInnerState_EnableArmMotors1_ERROR <<exitPoint>> #ff3333
	state eInnerState_EnableArmMotors1_Node_1 <<choice>>
	[*] ---> eInnerState_EnableArmMotors1_Node_1 : START
	state "fbEventHandler(SYSTEM_IN_UNEXPECTED_STATE)" as eInnerState_EnableArmMotors1_Node_3 
		state eInnerState_EnableArmMotors1_Node_4 <<choice>>
		state "fbEventHandler(UNABLE_TO_START_TASK)" as eInnerState_EnableArmMotors1_Node_6 
		state "fbArmMotors.ErrorAck:=TRUE;" as eInnerState_EnableArmMotors1_Node_7 
		state "fbArmMotors.bEnable:=TRUE;" as eInnerState_EnableArmMotors1_Node_8 
		state "ChangeState" as eInnerState_EnableArmMotors1_Node_9 
	eInnerState_EnableArmMotors1_Node_8 ---> eInnerState_EnableArmMotors1_Node_9
	eInnerState_EnableArmMotors1_Node_9 ---> [*] : eInnerState_EnableArmMotors1->eInnerState_EnableArmMotors2
	}
	state eInnerState_EnableArmMotors2 #lightblue {
state "ERROR" as eInnerState_EnableArmMotors2_ERROR <<exitPoint>> #ff3333
	state eInnerState_EnableArmMotors2_Node_1 <<choice>>
	[*] ---> eInnerState_EnableArmMotors2_Node_1 : START
		state eInnerState_EnableArmMotors2_Node_3 <<choice>>
		state "fbEventHandler(TASK_FAILED)" as eInnerState_EnableArmMotors2_Node_5 
		state "fbArmMotors.ErrorAck:=TRUE;" as eInnerState_EnableArmMotors2_Node_6 
		state "ChangeState" as eInnerState_EnableArmMotors2_Node_7 
	eInnerState_EnableArmMotors2_Node_3 ---> eInnerState_EnableArmMotors2_Node_7 : (NOT (fbArmMotors.bError))
	eInnerState_EnableArmMotors2_Node_7 ---> [*] : eInnerState_EnableArmMotors2->eInnerState_SetupWeightCompOn1
	}
	state eInnerState_SetupWeightCompOn1 #lightblue {
state "ERROR" as eInnerState_SetupWeightCompOn1_ERROR <<exitPoint>> #ff3333
	state eInnerState_SetupWeightCompOn1_Node_1 <<choice>>
	[*] ---> eInnerState_SetupWeightCompOn1_Node_1 : START
	state "tWeightCompOnTime := DateTime.GVL_DATE_TIME;" as eInnerState_SetupWeightCompOn1_Node_3 
	state "fbArmMotors.bZeroOutput := FALSE;" as eInnerState_SetupWeightCompOn1_Node_4 
	state "fbKnS.WeightCompOn := TRUE;" as eInnerState_SetupWeightCompOn1_Node_5 
	state "fbKnS.ForceFeedbackOn := FALSE;" as eInnerState_SetupWeightCompOn1_Node_6 
	state "ChangeState" as eInnerState_SetupWeightCompOn1_Node_7 
	eInnerState_SetupWeightCompOn1_Node_6 ---> eInnerState_SetupWeightCompOn1_Node_7
	eInnerState_SetupWeightCompOn1_Node_7 ---> [*] : eInnerState_SetupWeightCompOn1->eInnerState_SetupWeightCompOn2
	}
	state eInnerState_SetupWeightCompOn2 #lightblue {
state "ERROR" as eInnerState_SetupWeightCompOn2_ERROR <<exitPoint>> #ff3333
	state eInnerState_SetupWeightCompOn2_Node_1 <<choice>>
	[*] ---> eInnerState_SetupWeightCompOn2_Node_1 : START
		state eInnerState_SetupWeightCompOn2_Node_3 <<choice>>
		state "bStop := FALSE;" as eInnerState_SetupWeightCompOn2_Node_5 
		state "ChangeState" as eInnerState_SetupWeightCompOn2_Node_6 
	eInnerState_SetupWeightCompOn2_Node_5 ---> eInnerState_SetupWeightCompOn2_Node_6
	eInnerState_SetupWeightCompOn2_Node_6 ---> [*] : eInnerState_SetupWeightCompOn2->eInnerState_StartShuttingDown
		state eInnerState_SetupWeightCompOn2_Node_7 <<choice>>
		state "ChangeState" as eInnerState_SetupWeightCompOn2_Node_8 
	eInnerState_SetupWeightCompOn2_Node_7 ---> eInnerState_SetupWeightCompOn2_Node_8 : (NOT bBothArmsDocked)
	eInnerState_SetupWeightCompOn2_Node_8 ---> [*] : eInnerState_SetupWeightCompOn2->eInnerState_Operational1
		state "ChangeState" as eInnerState_SetupWeightCompOn2_Node_9 
	eInnerState_SetupWeightCompOn2_Node_7 ---> eInnerState_SetupWeightCompOn2_Node_9 : (NOT bBothArmsDocked)
	eInnerState_SetupWeightCompOn2_Node_9 ---> [*] : eInnerState_SetupWeightCompOn2->eInnerState_SetupWeightCompOff1
		state "fbArmMotors.aJointTorques := fbKnS.aJointTorques;" as eInnerState_SetupWeightCompOn2_Node_10 
	state eInnerState_SetupWeightCompOn2_Node_4 <<join>>
	}
	state eInnerState_SetupWeightCompOff1 #lightblue {
state "ERROR" as eInnerState_SetupWeightCompOff1_ERROR <<exitPoint>> #ff3333
	state eInnerState_SetupWeightCompOff1_Node_1 <<choice>>
	[*] ---> eInnerState_SetupWeightCompOff1_Node_1 : START
	state "fbArmMotors.bZeroOutput := TRUE;" as eInnerState_SetupWeightCompOff1_Node_3 
	state "ChangeState" as eInnerState_SetupWeightCompOff1_Node_4 
	eInnerState_SetupWeightCompOff1_Node_3 ---> eInnerState_SetupWeightCompOff1_Node_4
	eInnerState_SetupWeightCompOff1_Node_4 ---> [*] : eInnerState_SetupWeightCompOff1->eInnerState_SetupWeightCompOff2
	}
	state eInnerState_SetupWeightCompOff2 #lightblue {
state "ERROR" as eInnerState_SetupWeightCompOff2_ERROR <<exitPoint>> #ff3333
	state eInnerState_SetupWeightCompOff2_Node_1 <<choice>>
	[*] ---> eInnerState_SetupWeightCompOff2_Node_1 : START
		state eInnerState_SetupWeightCompOff2_Node_3 <<choice>>
		state "bStop := FALSE;" as eInnerState_SetupWeightCompOff2_Node_5 
		state "ChangeState" as eInnerState_SetupWeightCompOff2_Node_6 
	eInnerState_SetupWeightCompOff2_Node_5 ---> eInnerState_SetupWeightCompOff2_Node_6
	eInnerState_SetupWeightCompOff2_Node_6 ---> [*] : eInnerState_SetupWeightCompOff2->eInnerState_StartShuttingDown
		state eInnerState_SetupWeightCompOff2_Node_7 <<choice>>
		state "ChangeState" as eInnerState_SetupWeightCompOff2_Node_8 
	eInnerState_SetupWeightCompOff2_Node_7 ---> eInnerState_SetupWeightCompOff2_Node_8 : (NOT bBothArmsDocked)
	eInnerState_SetupWeightCompOff2_Node_8 ---> [*] : eInnerState_SetupWeightCompOff2->eInnerState_Operational1
		state eInnerState_SetupWeightCompOff2_Node_9 <<choice>>
		state "ChangeState" as eInnerState_SetupWeightCompOff2_Node_10 
	eInnerState_SetupWeightCompOff2_Node_9 ---> eInnerState_SetupWeightCompOff2_Node_10 : (bMotionWhileDocked)
	eInnerState_SetupWeightCompOff2_Node_10 ---> [*] : eInnerState_SetupWeightCompOff2->eInnerState_SetupWeightCompOn1
	}
	state eInnerState_Operational1 #lightblue {
state "ERROR" as eInnerState_Operational1_ERROR <<exitPoint>> #ff3333
	state eInnerState_Operational1_Node_1 <<choice>>
	[*] ---> eInnerState_Operational1_Node_1 : START
	state "fbArmMotors.bZeroOutput := FALSE;" as eInnerState_Operational1_Node_3 
	state "fbKnS.WeightCompOn := TRUE;" as eInnerState_Operational1_Node_4 
	state "fbKnS.ForceFeedbackOn := TRUE;" as eInnerState_Operational1_Node_5 
	state "ChangeState" as eInnerState_Operational1_Node_6 
	eInnerState_Operational1_Node_5 ---> eInnerState_Operational1_Node_6
	eInnerState_Operational1_Node_6 ---> [*] : eInnerState_Operational1->eInnerState_Operational2
	}
	state eInnerState_Operational2 #lightblue {
state "ERROR" as eInnerState_Operational2_ERROR <<exitPoint>> #ff3333
	state eInnerState_Operational2_Node_1 <<choice>>
	[*] ---> eInnerState_Operational2_Node_1 : START
		state eInnerState_Operational2_Node_3 <<choice>>
		state "ChangeState" as eInnerState_Operational2_Node_5 
	eInnerState_Operational2_Node_3 ---> eInnerState_Operational2_Node_5 : (bRemoteError\nOR bJointError)
	eInnerState_Operational2_Node_5 ---> [*] : eInnerState_Operational2->eInnerState_ErrorWaitingForDock
		state eInnerState_Operational2_Node_6 <<choice>>
		state "bStop := FALSE;" as eInnerState_Operational2_Node_8 
		state "ChangeState" as eInnerState_Operational2_Node_9 
	eInnerState_Operational2_Node_8 ---> eInnerState_Operational2_Node_9
	eInnerState_Operational2_Node_9 ---> [*] : eInnerState_Operational2->eInnerState_StartShuttingDown
		state eInnerState_Operational2_Node_10 <<choice>>
		state "ChangeState" as eInnerState_Operational2_Node_11 
	eInnerState_Operational2_Node_10 ---> eInnerState_Operational2_Node_11 : (bBothArmsDocked)
	eInnerState_Operational2_Node_11 ---> [*] : eInnerState_Operational2->eInnerState_SetupWeightCompOn1
		state "stDataFromRM := fbRemoteManipulator.DataFromKuka;" as eInnerState_Operational2_Node_12 
		state "fbKnS.aForceFeedback := stDataFromRM.aKukaTipForce;" as eInnerState_Operational2_Node_13 
		state "fbArmMotors.aJointTorques := fbKnS.aJointTorques;" as eInnerState_Operational2_Node_14 
		state "fbRemoteManipulator.TimeDerivativePosition := fbKnS.aPositionChange;" as eInnerState_Operational2_Node_15 
		state "fbRemoteManipulator.TimeDerivativeOrientation := fbKnS.aOrientationChange;" as eInnerState_Operational2_Node_16 
		state "fbRemoteManipulator.ToolActuation := fbTool.fActuationLevel;" as eInnerState_Operational2_Node_17 
		state "fbRemoteManipulator.ToolType := fbTool.eToolID;" as eInnerState_Operational2_Node_18 
		state "fbRemoteManipulator.EnableRM := fbFootSwitch.bClutchPressed;" as eInnerState_Operational2_Node_19 
		state "fbRemoteManipulator.bSendMotionCommands := fbFootSwitch.bClutchPressed;" as eInnerState_Operational2_Node_20 
	state eInnerState_Operational2_Node_7 <<join>>
	}
	state eInnerState_ErrorWaitingForDock #lightblue {
state "ERROR" as eInnerState_ErrorWaitingForDock_ERROR <<exitPoint>> #ff3333
	state eInnerState_ErrorWaitingForDock_Node_1 <<choice>>
	[*] ---> eInnerState_ErrorWaitingForDock_Node_1 : START
	}
	state eInnerState_StartShuttingDown #lightblue {
state "ERROR" as eInnerState_StartShuttingDown_ERROR <<exitPoint>> #ff3333
	state "fbKnS.bStop := TRUE;" as eInnerState_StartShuttingDown_Node_1 
	[*] ---> eInnerState_StartShuttingDown_Node_1 : START
	state "fbArmMotors.bDisable := TRUE;" as eInnerState_StartShuttingDown_Node_2 
	state "fbRemoteManipulator.bEndCommunication := TRUE;" as eInnerState_StartShuttingDown_Node_3 
	state "ChangeState" as eInnerState_StartShuttingDown_Node_4 
	eInnerState_StartShuttingDown_Node_3 ---> eInnerState_StartShuttingDown_Node_4
	eInnerState_StartShuttingDown_Node_4 ---> [*] : eInnerState_StartShuttingDown->eInnerState_DisableArmMotors
	}
	state eInnerState_DisableArmMotors #lightblue {
state "ERROR" as eInnerState_DisableArmMotors_ERROR <<exitPoint>> #ff3333
	state eInnerState_DisableArmMotors_Node_1 <<choice>>
	[*] ---> eInnerState_DisableArmMotors_Node_1 : START
		state eInnerState_DisableArmMotors_Node_3 <<choice>>
		state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_DisableArmMotors_Node_5 
		state "fbArmMotors.ErrorAck:=TRUE;" as eInnerState_DisableArmMotors_Node_6 
		state "ChangeState" as eInnerState_DisableArmMotors_Node_7 
	eInnerState_DisableArmMotors_Node_3 ---> eInnerState_DisableArmMotors_Node_7 : (NOT (fbArmMotors.bError))
	eInnerState_DisableArmMotors_Node_7 ---> [*] : eInnerState_DisableArmMotors->eInnerState_StopCommRM
	}
	state eInnerState_StopCommRM #lightblue {
state "ERROR" as eInnerState_StopCommRM_ERROR <<exitPoint>> #ff3333
	state eInnerState_StopCommRM_Node_1 <<choice>>
	[*] ---> eInnerState_StopCommRM_Node_1 : START
		state eInnerState_StopCommRM_Node_3 <<choice>>
		state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_StopCommRM_Node_5 
		state "fbRemoteManipulator.ErrorAck:=TRUE;" as eInnerState_StopCommRM_Node_6 
		state "ChangeState" as eInnerState_StopCommRM_Node_7 
	eInnerState_StopCommRM_Node_3 ---> eInnerState_StopCommRM_Node_7 : (NOT (fbRemoteManipulator.bError))
	eInnerState_StopCommRM_Node_7 ---> [*] : eInnerState_StopCommRM->eInnerState_StopDataProcessing
	}
	state eInnerState_StopDataProcessing #lightblue {
state "ERROR" as eInnerState_StopDataProcessing_ERROR <<exitPoint>> #ff3333
	state eInnerState_StopDataProcessing_Node_1 <<choice>>
	[*] ---> eInnerState_StopDataProcessing_Node_1 : START
		state eInnerState_StopDataProcessing_Node_3 <<choice>>
		state "fbEventHandler(UNABLE_TO_COMPLETE_TASK)" as eInnerState_StopDataProcessing_Node_5 
		state "fbKnS.ErrorAck:=TRUE;" as eInnerState_StopDataProcessing_Node_6 
		state "ChangeState" as eInnerState_StopDataProcessing_Node_7 
	eInnerState_StopDataProcessing_Node_3 ---> eInnerState_StopDataProcessing_Node_7 : (NOT (fbKnS.bError))
	eInnerState_StopDataProcessing_Node_7 ---> [*] : eInnerState_StopDataProcessing->eInnerState_WrapUp
	}
	state eInnerState_WrapUp #lightblue {
state "ERROR" as eInnerState_WrapUp_ERROR <<exitPoint>> #ff3333
	state "ChangeState" as eInnerState_WrapUp_Node_1 
	[*] ---> [*] : eInnerState_WrapUp->eInnerState_Idle
	}
	}
	eInnerState_Idle_Node_1 ---> eInnerState_Idle_Node_3 : (bStart)
	eInnerState_Idle ---> eInnerState_StartDataProcessing1 : eInnerState_Idle->eInnerState_StartDataProcessing1
	eInnerState_StartDataProcessing1_Node_1 ---> eInnerState_StartDataProcessing1_Node_3 : (fbKnS.Busy)
	eInnerState_StartDataProcessing1_Node_3 ---> eInnerState_StartDataProcessing1_ERROR : (fbKnS.Busy)
	eInnerState_StartDataProcessing1_Node_1 ---> eInnerState_StartDataProcessing1_Node_4 : (NOT (fbKnS.Busy))
	eInnerState_StartDataProcessing1_Node_4 ---> eInnerState_StartDataProcessing1_Node_6 : (fbKnS.bError)
	eInnerState_StartDataProcessing1_Node_6 ---> eInnerState_StartDataProcessing1_Node_7
	eInnerState_StartDataProcessing1_Node_7 ---> eInnerState_StartDataProcessing1_ERROR : (fbKnS.bError)
	eInnerState_StartDataProcessing1_Node_4 ---> eInnerState_StartDataProcessing1_Node_8 : (NOT (fbKnS.bError))
	eInnerState_StartDataProcessing1 ---> eInnerState_StartDataProcessing2 : eInnerState_StartDataProcessing1->eInnerState_StartDataProcessing2
	eInnerState_StartDataProcessing2 ---> eInnerState_StartCommRM1 : eInnerState_StartDataProcessing2->eInnerState_StartCommRM1
	eInnerState_StartDataProcessing2_Node_1 ---> eInnerState_StartDataProcessing2_Node_4 : (NOT (fbKnS.Processing))
	eInnerState_StartDataProcessing2_Node_4 ---> eInnerState_StartDataProcessing2_Node_6 : (fbKnS.bError)
	eInnerState_StartDataProcessing2_Node_6 ---> eInnerState_StartDataProcessing2_Node_7
	eInnerState_StartDataProcessing2_Node_7 ---> eInnerState_StartDataProcessing2_ERROR : (fbKnS.bError)
	eInnerState_StartCommRM1_Node_1 ---> eInnerState_StartCommRM1_Node_3 : (fbRemoteManipulator.Busy)
	eInnerState_StartCommRM1_Node_3 ---> eInnerState_StartCommRM1_ERROR : (fbRemoteManipulator.Busy)
	eInnerState_StartCommRM1_Node_1 ---> eInnerState_StartCommRM1_Node_4 : (NOT (fbRemoteManipulator.Busy))
	eInnerState_StartCommRM1_Node_4 ---> eInnerState_StartCommRM1_Node_6 : (fbRemoteManipulator.bError)
	eInnerState_StartCommRM1_Node_6 ---> eInnerState_StartCommRM1_Node_7
	eInnerState_StartCommRM1_Node_7 ---> eInnerState_StartCommRM1_ERROR : (fbRemoteManipulator.bError)
	eInnerState_StartCommRM1_Node_4 ---> eInnerState_StartCommRM1_Node_8 : (NOT (fbRemoteManipulator.bError))
	eInnerState_StartCommRM1 ---> eInnerState_StartCommRM2 : eInnerState_StartCommRM1->eInnerState_StartCommRM2
	eInnerState_StartCommRM2_Node_1 ---> eInnerState_StartCommRM2_Node_3 : (fbRemoteManipulator.Failed)
	eInnerState_StartCommRM2_Node_3 ---> eInnerState_StartCommRM2_Node_4
	eInnerState_StartCommRM2_Node_4 ---> eInnerState_StartCommRM2_ERROR : (fbRemoteManipulator.Failed)
	eInnerState_StartCommRM2_Node_1 ---> eInnerState_StartCommRM2_Node_5 : (NOT (fbRemoteManipulator.Failed))
	eInnerState_StartCommRM2 ---> eInnerState_EnableArmMotors1 : eInnerState_StartCommRM2->eInnerState_EnableArmMotors1
	eInnerState_EnableArmMotors1_Node_1 ---> eInnerState_EnableArmMotors1_Node_3 : (fbArmMotors.Busy)
	eInnerState_EnableArmMotors1_Node_3 ---> eInnerState_EnableArmMotors1_ERROR : (fbArmMotors.Busy)
	eInnerState_EnableArmMotors1_Node_1 ---> eInnerState_EnableArmMotors1_Node_4 : (NOT (fbArmMotors.Busy))
	eInnerState_EnableArmMotors1_Node_4 ---> eInnerState_EnableArmMotors1_Node_6 : (fbArmMotors.bError)
	eInnerState_EnableArmMotors1_Node_6 ---> eInnerState_EnableArmMotors1_Node_7
	eInnerState_EnableArmMotors1_Node_7 ---> eInnerState_EnableArmMotors1_ERROR : (fbArmMotors.bError)
	eInnerState_EnableArmMotors1_Node_4 ---> eInnerState_EnableArmMotors1_Node_8 : (NOT (fbArmMotors.bError))
	eInnerState_EnableArmMotors1 ---> eInnerState_EnableArmMotors2 : eInnerState_EnableArmMotors1->eInnerState_EnableArmMotors2
	eInnerState_EnableArmMotors2_Node_1 ---> eInnerState_EnableArmMotors2_Node_3 : (NOT (fbArmMotors.Busy))
	eInnerState_EnableArmMotors2_Node_3 ---> eInnerState_EnableArmMotors2_Node_5 : (fbArmMotors.bError)
	eInnerState_EnableArmMotors2_Node_5 ---> eInnerState_EnableArmMotors2_Node_6
	eInnerState_EnableArmMotors2_Node_6 ---> eInnerState_EnableArmMotors2_ERROR : (fbArmMotors.bError)
	eInnerState_EnableArmMotors2 ---> eInnerState_SetupWeightCompOn1 : eInnerState_EnableArmMotors2->eInnerState_SetupWeightCompOn1
	eInnerState_SetupWeightCompOn1_Node_1 ---> eInnerState_SetupWeightCompOn1_ERROR : (CheckForFailedChildren())
	eInnerState_SetupWeightCompOn1_Node_1 ---> eInnerState_SetupWeightCompOn1_Node_3 : (NOT (CheckForFailedChildren()))
	eInnerState_SetupWeightCompOn1_Node_3 ---> eInnerState_SetupWeightCompOn1_Node_4
	eInnerState_SetupWeightCompOn1_Node_4 ---> eInnerState_SetupWeightCompOn1_Node_5
	eInnerState_SetupWeightCompOn1_Node_5 ---> eInnerState_SetupWeightCompOn1_Node_6
	eInnerState_SetupWeightCompOn1 ---> eInnerState_SetupWeightCompOn2 : eInnerState_SetupWeightCompOn1->eInnerState_SetupWeightCompOn2
	eInnerState_SetupWeightCompOn2_Node_1 ---> eInnerState_SetupWeightCompOn2_ERROR : (CheckForFailedChildren())
	eInnerState_SetupWeightCompOn2_Node_1 ---> eInnerState_SetupWeightCompOn2_Node_3 : (NOT (CheckForFailedChildren()))
	eInnerState_SetupWeightCompOn2_Node_3 ---> eInnerState_SetupWeightCompOn2_Node_5 : (bStop)
	eInnerState_SetupWeightCompOn2 ---> eInnerState_StartShuttingDown : eInnerState_SetupWeightCompOn2->eInnerState_StartShuttingDown
	eInnerState_SetupWeightCompOn2_Node_3 ---> eInnerState_SetupWeightCompOn2_Node_7 : (NOT (bStop))
	eInnerState_SetupWeightCompOn2 ---> eInnerState_Operational1 : eInnerState_SetupWeightCompOn2->eInnerState_Operational1
	eInnerState_SetupWeightCompOn2 ---> eInnerState_SetupWeightCompOff1 : eInnerState_SetupWeightCompOn2->eInnerState_SetupWeightCompOff1
	eInnerState_SetupWeightCompOn2_Node_7 ---> eInnerState_SetupWeightCompOn2_Node_10 : (bBothArmsDocked)
	eInnerState_SetupWeightCompOn2_Node_10 ---> eInnerState_SetupWeightCompOn2_Node_4
	eInnerState_SetupWeightCompOff1_Node_1 ---> eInnerState_SetupWeightCompOff1_ERROR : (CheckForFailedChildren())
	eInnerState_SetupWeightCompOff1_Node_1 ---> eInnerState_SetupWeightCompOff1_Node_3 : (NOT (CheckForFailedChildren()))
	eInnerState_SetupWeightCompOff1 ---> eInnerState_SetupWeightCompOff2 : eInnerState_SetupWeightCompOff1->eInnerState_SetupWeightCompOff2
	eInnerState_SetupWeightCompOff2_Node_1 ---> eInnerState_SetupWeightCompOff2_ERROR : (CheckForFailedChildren())
	eInnerState_SetupWeightCompOff2_Node_1 ---> eInnerState_SetupWeightCompOff2_Node_3 : (NOT (CheckForFailedChildren()))
	eInnerState_SetupWeightCompOff2_Node_3 ---> eInnerState_SetupWeightCompOff2_Node_5 : (bStop)
	eInnerState_SetupWeightCompOff2 ---> eInnerState_StartShuttingDown : eInnerState_SetupWeightCompOff2->eInnerState_StartShuttingDown
	eInnerState_SetupWeightCompOff2_Node_3 ---> eInnerState_SetupWeightCompOff2_Node_7 : (NOT (bStop))
	eInnerState_SetupWeightCompOff2 ---> eInnerState_Operational1 : eInnerState_SetupWeightCompOff2->eInnerState_Operational1
	eInnerState_SetupWeightCompOff2_Node_7 ---> eInnerState_SetupWeightCompOff2_Node_9 : (bBothArmsDocked)
	eInnerState_SetupWeightCompOff2 ---> eInnerState_SetupWeightCompOn1 : eInnerState_SetupWeightCompOff2->eInnerState_SetupWeightCompOn1
	eInnerState_Operational1_Node_1 ---> eInnerState_Operational1_ERROR : (CheckForFailedChildren())
	eInnerState_Operational1_Node_1 ---> eInnerState_Operational1_Node_3 : (NOT (CheckForFailedChildren()))
	eInnerState_Operational1_Node_3 ---> eInnerState_Operational1_Node_4
	eInnerState_Operational1_Node_4 ---> eInnerState_Operational1_Node_5
	eInnerState_Operational1 ---> eInnerState_Operational2 : eInnerState_Operational1->eInnerState_Operational2
	eInnerState_Operational2_Node_1 ---> eInnerState_Operational2_Node_3 : (CheckForFailedChildren())
	eInnerState_Operational2 ---> eInnerState_ErrorWaitingForDock : eInnerState_Operational2->eInnerState_ErrorWaitingForDock
	eInnerState_Operational2_Node_3 ---> eInnerState_Operational2_ERROR : (NOT (bRemoteError\nOR bJointError))
	eInnerState_Operational2_Node_1 ---> eInnerState_Operational2_Node_6 : (NOT (CheckForFailedChildren()))
	eInnerState_Operational2_Node_6 ---> eInnerState_Operational2_Node_8 : (bStop)
	eInnerState_Operational2 ---> eInnerState_StartShuttingDown : eInnerState_Operational2->eInnerState_StartShuttingDown
	eInnerState_Operational2_Node_6 ---> eInnerState_Operational2_Node_10 : (NOT (bStop))
	eInnerState_Operational2 ---> eInnerState_SetupWeightCompOn1 : eInnerState_Operational2->eInnerState_SetupWeightCompOn1
	eInnerState_Operational2_Node_10 ---> eInnerState_Operational2_Node_12 : (NOT (bBothArmsDocked))
	eInnerState_Operational2_Node_12 ---> eInnerState_Operational2_Node_13
	eInnerState_Operational2_Node_13 ---> eInnerState_Operational2_Node_14
	eInnerState_Operational2_Node_14 ---> eInnerState_Operational2_Node_15
	eInnerState_Operational2_Node_15 ---> eInnerState_Operational2_Node_16
	eInnerState_Operational2_Node_16 ---> eInnerState_Operational2_Node_17
	eInnerState_Operational2_Node_17 ---> eInnerState_Operational2_Node_18
	eInnerState_Operational2_Node_18 ---> eInnerState_Operational2_Node_19
	eInnerState_Operational2_Node_19 ---> eInnerState_Operational2_Node_20
	eInnerState_Operational2_Node_20 ---> eInnerState_Operational2_Node_7
	eInnerState_ErrorWaitingForDock_Node_1 ---> eInnerState_ErrorWaitingForDock_ERROR : (bBothArmsDocked)
	eInnerState_StartShuttingDown_Node_1 ---> eInnerState_StartShuttingDown_Node_2
	eInnerState_StartShuttingDown_Node_2 ---> eInnerState_StartShuttingDown_Node_3
	eInnerState_StartShuttingDown ---> eInnerState_DisableArmMotors : eInnerState_StartShuttingDown->eInnerState_DisableArmMotors
	eInnerState_DisableArmMotors_Node_1 ---> eInnerState_DisableArmMotors_Node_3 : (NOT (fbArmMotors.Busy))
	eInnerState_DisableArmMotors_Node_3 ---> eInnerState_DisableArmMotors_Node_5 : (fbArmMotors.bError)
	eInnerState_DisableArmMotors_Node_5 ---> eInnerState_DisableArmMotors_Node_6
	eInnerState_DisableArmMotors_Node_6 ---> eInnerState_DisableArmMotors_ERROR : (fbArmMotors.bError)
	eInnerState_DisableArmMotors ---> eInnerState_StopCommRM : eInnerState_DisableArmMotors->eInnerState_StopCommRM
	eInnerState_StopCommRM_Node_1 ---> eInnerState_StopCommRM_Node_3 : (NOT (fbRemoteManipulator.Busy))
	eInnerState_StopCommRM_Node_3 ---> eInnerState_StopCommRM_Node_5 : (fbRemoteManipulator.bError)
	eInnerState_StopCommRM_Node_5 ---> eInnerState_StopCommRM_Node_6
	eInnerState_StopCommRM_Node_6 ---> eInnerState_StopCommRM_ERROR : (fbRemoteManipulator.bError)
	eInnerState_StopCommRM ---> eInnerState_StopDataProcessing : eInnerState_StopCommRM->eInnerState_StopDataProcessing
	eInnerState_StopDataProcessing_Node_1 ---> eInnerState_StopDataProcessing_Node_3 : (NOT (fbKnS.Busy))
	eInnerState_StopDataProcessing_Node_3 ---> eInnerState_StopDataProcessing_Node_5 : (fbKnS.bError)
	eInnerState_StopDataProcessing_Node_5 ---> eInnerState_StopDataProcessing_Node_6
	eInnerState_StopDataProcessing_Node_6 ---> eInnerState_StopDataProcessing_ERROR : (fbKnS.bError)
	eInnerState_StopDataProcessing ---> eInnerState_WrapUp : eInnerState_StopDataProcessing->eInnerState_WrapUp
	eInnerState_WrapUp ---> eInnerState_Idle : eInnerState_WrapUp->eInnerState_Idle
eInnerState : 
eInnerState : 


}

@enduml
